## Rats in the Restaurant - Data Cleaning and Transformation
#### County of Los Angeles Open Data Source
* Dataset #1: https://data.lacounty.gov/Health/LOS-ANGELES-COUNTY-RESTAURANT-AND-MARKET-INSPECTIO/6ni6-h5kp
* Dataset #2: https://data.lacounty.gov/Health/LOS-ANGELES-COUNTY-RESTAURANT-AND-MARKET-VIOLATION/8jyd-4pv9
* Dataset #3: https://data.lacounty.gov/Health/Los-Angeles-County-City-and-Community-Health-Profi/capb-kusk

In [1]:
# Import dependencies
import pandas as pd
import re
import datetime as dt

In [2]:
# Get datasets
inspections_dataset = pd.read_csv("./Resources/LOS_ANGELES_COUNTY_RESTAURANT_AND_MARKET_INSPECTIONS.csv")
violations_dataset = pd.read_csv("./Resources/LOS_ANGELES_COUNTY_RESTAURANT_AND_MARKET_VIOLATIONS.csv")
communityhealth_dataset = pd.read_csv("./Resources/Los_Angeles_County_City_and_Community_Health_Profiles_2018.csv")

In [3]:
# Expand output display to view all
pd.set_option('display.max_columns', 999)

In [4]:
# Create Inspections DF
inspections_df = pd.DataFrame(inspections_dataset)
inspections_df.head()

,ACTIVITY DATE,OWNER ID,OWNER NAME,FACILITY ID,FACILITY NAME,RECORD ID,PROGRAM NAME,PROGRAM STATUS,PROGRAM ELEMENT (PE),PE DESCRIPTION,FACILITY ADDRESS,FACILITY CITY,FACILITY STATE,FACILITY ZIP,SERVICE CODE,SERVICE DESCRIPTION,SCORE,GRADE,SERIAL NUMBER,EMPLOYEE ID,Location
0,09/10/2018,OW0105348,"GUCKENHEIMER SERVICES, LLC.",FA0242046,SERVERY- NICKELODEON,PR0190194,SERVERY- NICKELODEON,ACTIVE,1635,RESTAURANT (31-60) SEATS HIGH RISK,203 W OLIVE AVE # C,BURBANK,CA,91502,1,ROUTINE INSPECTION,96,A,DARRFUZBW,EE0000495,POINT (-118.314661 34.175253)
1,07/19/2018,OW0246461,ANASTACIOS POLITIS,FA0252769,TOMS JR BURGERS,PR0202127,TOMS JR BURGERS,ACTIVE,1632,RESTAURANT (0-30) SEATS HIGH RISK,1030 W MARTIN LUTHER KING JR BLVD STE 108,LOS ANGELES,CA,90037-1867,1,ROUTINE INSPECTION,98,A,DA0XQVMTN,EE0001130,POINT (-118.292543 34.010859)
2,08/15/2018,OW0010130,DJ BIBINGKAHAN CORPORATION,FA0011237,DJ BIBINGKAHAN,PR0035416,DJ BIBINGKAHAN BAKESHOP,ACTIVE,1631,RESTAURANT (0-30) SEATS MODERATE RISK,1515 E AMAR RD,WEST COVINA,CA,91792,1,ROUTINE INSPECTION,98,A,DAMPOJNY8,EE0000500,POINT (-117.913926 34.030964)
3,07/16/2018,OW0020051,KULWINDER KAUR,FA0061073,DOROSE LIQUOR,PR0027907,DOROSE LIQUOR,ACTIVE,1610,"FOOD MKT RETAIL (1-1,999 SF) LOW RISK",13560 ROSCOE BLVD,PANORAMA CITY,CA,91402,1,ROUTINE INSPECTION,91,A,DAUTU3DPD,EE0000045,POINT (-118.428399 34.221664)
4,09/07/2018,OW0246329,JUAN C OROZCO,FA0252595,MEJICO GRILL AND TEQUILLA LOUNGE,PR0201914,MEJICO GRILL AND TEQUILLA LOUNGE,ACTIVE,1641,RESTAURANT (151 + ) SEATS HIGH RISK,29002 AGOURA RD,AGOURA HILLS,CA,91301,1,ROUTINE INSPECTION,90,A,DAUEU4NGF,EE0000526,POINT (-118.756808 34.143452)

In [5]:
# Create Violations DF
violations_df = pd.DataFrame(violations_dataset)
violations_df.head()

,SERIAL NUMBER,VIOLATION STATUS,VIOLATION CODE,VIOLATION DESCRIPTION,POINTS
0,DA000211Z,OUT OF COMPLIANCE,F006,# 06. Adequate handwashing facilities supplied...,2.0
1,DA000211Z,OUT OF COMPLIANCE,F044,"# 44. Floors, walls and ceilings: properly bui...",1.0
2,DA000211Z,OUT OF COMPLIANCE,F014,# 14. Food contact surfaces: clean and sanitized,2.0
3,DA000211Z,OUT OF COMPLIANCE,F029,"# 29. Toxic substances properly identified, st...",1.0
4,DA000211Z,OUT OF COMPLIANCE,F035,# 35. Equipment/Utensils - approved; installed...,1.0

In [6]:
# Create Community Health DF
community_health_df = pd.DataFrame(communityhealth_dataset)
community_health_df.head()

,GEONAME,Pop_Tot,Prop_18y,Prop_64y,Prop_65y+,Prop_Blk,Prop_Lat,Prop_Whi,Prop_Asi,Prop_Ami,Prop_NHO,Prop_FPL1,Prop_FPL2,Prop_forb,Prop_Eng,LE,Prop_prsc,Prop_3rdg,Prop_edLH,Prop_edHG,Prop_edSC,Prop_edCG,MHI,No_libr,Prop_empl,Prop_emsu,Prop_vote,Rte_resp,Prop_PA,Prop_groc,Prop_60mi,No_farm,No_EBT,Prop_foin,No_CalF,Rte_CalF,Prop_FRPM,Prop_obse,Prop_DM,Rte_coin,Rte_brin,Prop_smok,Rte_luca,Rte_COPD,Rte_CVD,Prop_hbu1,Prop_hbu2,Prop_ownr,Prop_rentr,No_hless,Prop_asth,Rte_crim,Rte_hom,Rte_alco,Propt_envi,No_gasw,Rte_te17,Rte_te19,Prop_LBW,Rte_IMR,Prop_1stt,Prop_depr,Rte_suic,Rte_UOD,Rte_syin,Rte_goin,Rte_hiv,Prop_uinC,Prop_uinA,Prop_duinC,Prop_duinA,Propt_HPI,Rte_mein,Rte_cein,Rte_luin,Prop_fru,Prop_bev,Prop_hyp,Prop_marj,Prop_HI,Prop_grad,Prop_trua
0,Alhambra,86705,0.1831,0.6504,0.1665,0.0133,0.3435,0.0913,0.5498,0.0014,0.0007,0.1303,0.3356,0.5021,0.2112,84.55,0.665,0.5353,0.1934,0.2280,0.2497,0.3289,53582,1.0,0.940,0.3850,0.6235,0.7706,0.2731,0.5239,0.111,1,1,**,"15,799",0.3300,0.6598,0.1358,0.1040,45.7963,125.9019,0.1272,25.4872,21.7535,170.914,0.447,0.232,0.404,0.596,64,0.0449,168,**,12,6,2,2.1042,9.1180,0.0815,3.1022,0.8614,0.0523,7,3,14,66,208,0.0598,0.2070,0.0929,0.2291,43.3,**,**,34.6,0.2,0.2,0.2,0.1,0.0,1.0,0.1
1,Altadena,42525,0.2072,0.6221,0.1707,0.2374,0.2905,0.4129,0.0553,0.0019,0.0020,0.0988,0.2281,0.2021,0.0379,82.11,0.740,0.3942,0.1050,0.1397,0.2918,0.4635,86050,2.0,0.920,0.7335,0.7360,1.0975,0.3482,0.4524,0.120,1,1,**,-,-,0.5590,0.2441,0.1358,38.3670,189.2143,0.1129,25.2189,28.4887,211.035,0.401,0.193,0.719,0.281,58,0.0915,162,**,6,62,0,3.9610,7.6173,0.0703,**,0.8859,0.1099,10,8,19,119,330,0.0333,0.1745,0.0660,0.0924,75.5,33.8,**,35.3,0.1,0.3,0.3,0.2,0.1,0.9,0.4
2,Arcadia,56992,0.1794,0.6389,0.1817,0.0115,0.1250,0.2304,0.6315,0.0014,0.0003,0.0774,0.2042,0.4877,0.1888,85.42,0.675,0.7927,0.0789,0.1601,0.2430,0.5180,79934,1.0,0.941,0.5691,0.6271,1.9654,0.2662,0.5110,0.131,0,0,**,"6,638",0.1800,0.2066,0.0570,0.0819,32.9547,145.2497,0.1285,22.5416,22.0580,173.371,0.402,0.214,0.596,0.404,12,**,146,**,19,27,2,**,**,0.0590,**,0.8588,0.0493,9,**,8,46,56,0.0564,0.1245,0.1232,0.1876,73.4,22.0,**,29.5,0.1,0.2,0.2,0.0,0.0,1.0,0.1
3,Azusa,49479,0.2507,0.6538,0.0956,0.0292,0.6838,0.1938,0.0895,0.0024,0.0013,0.1636,0.3935,0.3082,0.1156,81.16,0.439,0.3390,0.2232,0.2932,0.2873,0.1962,53135,1.0,0.927,0.6201,0.6569,1.0168,0.3759,0.5997,0.121,0,0,0.2006,"8,868",0.5800,0.8060,0.2607,0.1198,31.3309,134.9485,0.1174,34.8652,33.1891,218.754,0.474,0.240,0.527,0.473,55,0.0660,354,6,14,48,0,3.5084,9.2802,0.0681,**,0.8810,0.0895,8,**,27,116,196,0.0708,0.2404,0.1117,0.1918,34.2,**,**,29.7,0.1,0.4,0.2,0.1,0.0,0.9,0.0
4,Baldwin Park,74438,0.2623,0.6330,0.1047,0.0099,0.7934,0.0432,0.1514,0.0012,0.0008,0.1591,0.4116,0.4453,0.1908,82.99,0.470,0.3227,0.3740,0.3170,0.1962,0.1128,51742,1.0,0.898,0.5712,0.6318,0.3406,0.3164,0.5444,0.125,1,1,0.2531,"14,206",0.7400,0.8729,0.2652,0.1307,43.8584,110.0378,0.1045,28.2446,31.2708,195.522,0.498,0.227,0.572,0.428,111,0.0904,391,5,10,9,0,7.3997,20.1220,0.0856,4.1881,0.8827,0.0544,**,5,21,98,171,0.0582,0.3259,0.0704,0.1874,22.3,**,**,26.5,0.1,0.4,0.3,0.1,0.0,1.0,0.4

### INSPECTIONS_DF DATA CLEANUP:
#### Get data from  'PE DESCRIPTION' column
* Type
* No. of seats
* Risk

In [7]:
#Remove all 'PE DESCRIPTION' that are not restaurants
inspections_df = inspections_df.loc[inspections_df['PE DESCRIPTION'].str.contains('RESTAURANT')]
inspections_df.head()

,ACTIVITY DATE,OWNER ID,OWNER NAME,FACILITY ID,FACILITY NAME,RECORD ID,PROGRAM NAME,PROGRAM STATUS,PROGRAM ELEMENT (PE),PE DESCRIPTION,FACILITY ADDRESS,FACILITY CITY,FACILITY STATE,FACILITY ZIP,SERVICE CODE,SERVICE DESCRIPTION,SCORE,GRADE,SERIAL NUMBER,EMPLOYEE ID,Location
0,09/10/2018,OW0105348,"GUCKENHEIMER SERVICES, LLC.",FA0242046,SERVERY- NICKELODEON,PR0190194,SERVERY- NICKELODEON,ACTIVE,1635,RESTAURANT (31-60) SEATS HIGH RISK,203 W OLIVE AVE # C,BURBANK,CA,91502,1,ROUTINE INSPECTION,96,A,DARRFUZBW,EE0000495,POINT (-118.314661 34.175253)
1,07/19/2018,OW0246461,ANASTACIOS POLITIS,FA0252769,TOMS JR BURGERS,PR0202127,TOMS JR BURGERS,ACTIVE,1632,RESTAURANT (0-30) SEATS HIGH RISK,1030 W MARTIN LUTHER KING JR BLVD STE 108,LOS ANGELES,CA,90037-1867,1,ROUTINE INSPECTION,98,A,DA0XQVMTN,EE0001130,POINT (-118.292543 34.010859)
2,08/15/2018,OW0010130,DJ BIBINGKAHAN CORPORATION,FA0011237,DJ BIBINGKAHAN,PR0035416,DJ BIBINGKAHAN BAKESHOP,ACTIVE,1631,RESTAURANT (0-30) SEATS MODERATE RISK,1515 E AMAR RD,WEST COVINA,CA,91792,1,ROUTINE INSPECTION,98,A,DAMPOJNY8,EE0000500,POINT (-117.913926 34.030964)
4,09/07/2018,OW0246329,JUAN C OROZCO,FA0252595,MEJICO GRILL AND TEQUILLA LOUNGE,PR0201914,MEJICO GRILL AND TEQUILLA LOUNGE,ACTIVE,1641,RESTAURANT (151 + ) SEATS HIGH RISK,29002 AGOURA RD,AGOURA HILLS,CA,91301,1,ROUTINE INSPECTION,90,A,DAUEU4NGF,EE0000526,POINT (-118.756808 34.143452)
5,09/18/2018,OW0123199,REDONDO ENTERPRISES LLC,FA0158101,MCDONALD'S #10681,PR0146191,MCDONALD'S #10681,ACTIVE,1637,RESTAURANT (61-150) SEATS MODERATE RISK,5725 FLORENCE AVE,BELL GARDENS,CA,90201,1,ROUTINE INSPECTION,91,A,DARQIUA45,EE0000437,POINT (-118.163665 33.967791)

In [8]:
# Get 'type', 'seats', and 'risk' from 'PE DESCRIPTION' and add them as columns to the Inspections DF
def find_est(str):
    est=re.compile('.+(?=\()')
    return est.search(str).group(0)

def find_size(str):
    size=re.compile('(?<=\().+(?=\))')
    return size.search(str).group(0)

def find_risk(str):
    return (' ').join(str.split(' ')[-2:])

inspections_df['TYPE'] = inspections_df['PE DESCRIPTION'].apply(find_est)
inspections_df['SEATS'] = inspections_df['PE DESCRIPTION'].apply(find_size)
inspections_df['RISK'] = inspections_df['PE DESCRIPTION'].apply(find_risk)

In [9]:
# Display DF
inspections_df.head()

,ACTIVITY DATE,OWNER ID,OWNER NAME,FACILITY ID,FACILITY NAME,RECORD ID,PROGRAM NAME,PROGRAM STATUS,PROGRAM ELEMENT (PE),PE DESCRIPTION,FACILITY ADDRESS,FACILITY CITY,FACILITY STATE,FACILITY ZIP,SERVICE CODE,SERVICE DESCRIPTION,SCORE,GRADE,SERIAL NUMBER,EMPLOYEE ID,Location,TYPE,SEATS,RISK
0,09/10/2018,OW0105348,"GUCKENHEIMER SERVICES, LLC.",FA0242046,SERVERY- NICKELODEON,PR0190194,SERVERY- NICKELODEON,ACTIVE,1635,RESTAURANT (31-60) SEATS HIGH RISK,203 W OLIVE AVE # C,BURBANK,CA,91502,1,ROUTINE INSPECTION,96,A,DARRFUZBW,EE0000495,POINT (-118.314661 34.175253),RESTAURANT,31-60,HIGH RISK
1,07/19/2018,OW0246461,ANASTACIOS POLITIS,FA0252769,TOMS JR BURGERS,PR0202127,TOMS JR BURGERS,ACTIVE,1632,RESTAURANT (0-30) SEATS HIGH RISK,1030 W MARTIN LUTHER KING JR BLVD STE 108,LOS ANGELES,CA,90037-1867,1,ROUTINE INSPECTION,98,A,DA0XQVMTN,EE0001130,POINT (-118.292543 34.010859),RESTAURANT,0-30,HIGH RISK
2,08/15/2018,OW0010130,DJ BIBINGKAHAN CORPORATION,FA0011237,DJ BIBINGKAHAN,PR0035416,DJ BIBINGKAHAN BAKESHOP,ACTIVE,1631,RESTAURANT (0-30) SEATS MODERATE RISK,1515 E AMAR RD,WEST COVINA,CA,91792,1,ROUTINE INSPECTION,98,A,DAMPOJNY8,EE0000500,POINT (-117.913926 34.030964),RESTAURANT,0-30,MODERATE RISK
4,09/07/2018,OW0246329,JUAN C OROZCO,FA0252595,MEJICO GRILL AND TEQUILLA LOUNGE,PR0201914,MEJICO GRILL AND TEQUILLA LOUNGE,ACTIVE,1641,RESTAURANT (151 + ) SEATS HIGH RISK,29002 AGOURA RD,AGOURA HILLS,CA,91301,1,ROUTINE INSPECTION,90,A,DAUEU4NGF,EE0000526,POINT (-118.756808 34.143452),RESTAURANT,151 +,HIGH RISK
5,09/18/2018,OW0123199,REDONDO ENTERPRISES LLC,FA0158101,MCDONALD'S #10681,PR0146191,MCDONALD'S #10681,ACTIVE,1637,RESTAURANT (61-150) SEATS MODERATE RISK,5725 FLORENCE AVE,BELL GARDENS,CA,90201,1,ROUTINE INSPECTION,91,A,DARQIUA45,EE0000437,POINT (-118.163665 33.967791),RESTAURANT,61-150,MODERATE RISK

In [10]:
# Drop columns
inspections_df = inspections_df.drop(columns = ['OWNER ID', 
                                               'OWNER NAME',
                                               'RECORD ID', 
                                               'PROGRAM ELEMENT (PE)', 
                                               "PE DESCRIPTION", 
                                               'SERVICE CODE',
                                               'SERVICE DESCRIPTION',  
                                               'EMPLOYEE ID', 
                                               "TYPE", 
                                               "RISK"])
inspections_df.head()

,ACTIVITY DATE,FACILITY ID,FACILITY NAME,PROGRAM NAME,PROGRAM STATUS,FACILITY ADDRESS,FACILITY CITY,FACILITY STATE,FACILITY ZIP,SCORE,GRADE,SERIAL NUMBER,Location,SEATS
0,09/10/2018,FA0242046,SERVERY- NICKELODEON,SERVERY- NICKELODEON,ACTIVE,203 W OLIVE AVE # C,BURBANK,CA,91502,96,A,DARRFUZBW,POINT (-118.314661 34.175253),31-60
1,07/19/2018,FA0252769,TOMS JR BURGERS,TOMS JR BURGERS,ACTIVE,1030 W MARTIN LUTHER KING JR BLVD STE 108,LOS ANGELES,CA,90037-1867,98,A,DA0XQVMTN,POINT (-118.292543 34.010859),0-30
2,08/15/2018,FA0011237,DJ BIBINGKAHAN,DJ BIBINGKAHAN BAKESHOP,ACTIVE,1515 E AMAR RD,WEST COVINA,CA,91792,98,A,DAMPOJNY8,POINT (-117.913926 34.030964),0-30
4,09/07/2018,FA0252595,MEJICO GRILL AND TEQUILLA LOUNGE,MEJICO GRILL AND TEQUILLA LOUNGE,ACTIVE,29002 AGOURA RD,AGOURA HILLS,CA,91301,90,A,DAUEU4NGF,POINT (-118.756808 34.143452),151 +
5,09/18/2018,FA0158101,MCDONALD'S #10681,MCDONALD'S #10681,ACTIVE,5725 FLORENCE AVE,BELL GARDENS,CA,90201,91,A,DARQIUA45,POINT (-118.163665 33.967791),61-150

#### Get data from 'Location' column
* LAT
* LNG

In [11]:
# Display "Location" column
inspections_df[["Location"]].head()

                        Location
0  POINT (-118.314661 34.175253)
1  POINT (-118.292543 34.010859)
2  POINT (-117.913926 34.030964)
4  POINT (-118.756808 34.143452)
5  POINT (-118.163665 33.967791)

In [12]:
# Split column
location_data = inspections_df["Location"].str.split(n=2, expand=True)
location_data.head()

       0             1           2
0  POINT  (-118.314661  34.175253)
1  POINT  (-118.292543  34.010859)
2  POINT  (-117.913926  34.030964)
4  POINT  (-118.756808  34.143452)
5  POINT  (-118.163665  33.967791)

In [13]:
# Drop column '0' aka 'POINT'
lat_lng_values = location_data.drop(columns=[0])
lat_lng_values.head()

              1           2
0  (-118.314661  34.175253)
1  (-118.292543  34.010859)
2  (-117.913926  34.030964)
4  (-118.756808  34.143452)
5  (-118.163665  33.967791)

In [14]:
# Get 'LAT' column
lats_split = lat_lng_values[1].str.split(pat='(', expand=True)
lat = lats_split.drop(columns=[0])
lat.columns = ['LAT']
lat.head()

           LAT
0  -118.314661
1  -118.292543
2  -117.913926
4  -118.756808
5  -118.163665

In [15]:
# Get 'LNG' column
lng_split = lat_lng_values[2].str.split(pat=')', expand=True)
lng = lng_split.drop(columns=[1])
lng.columns = ['LNG']
lng.head()

         LNG
0  34.175253
1  34.010859
2  34.030964
4  34.143452
5  33.967791

In [16]:
# Merge 'LAT' into Inspections DF
inspections_df = inspections_df.merge(lat, left_index = True, right_index = True)
inspections_df.head()

,ACTIVITY DATE,FACILITY ID,FACILITY NAME,PROGRAM NAME,PROGRAM STATUS,FACILITY ADDRESS,FACILITY CITY,FACILITY STATE,FACILITY ZIP,SCORE,GRADE,SERIAL NUMBER,Location,SEATS,LAT
0,09/10/2018,FA0242046,SERVERY- NICKELODEON,SERVERY- NICKELODEON,ACTIVE,203 W OLIVE AVE # C,BURBANK,CA,91502,96,A,DARRFUZBW,POINT (-118.314661 34.175253),31-60,-118.314661
1,07/19/2018,FA0252769,TOMS JR BURGERS,TOMS JR BURGERS,ACTIVE,1030 W MARTIN LUTHER KING JR BLVD STE 108,LOS ANGELES,CA,90037-1867,98,A,DA0XQVMTN,POINT (-118.292543 34.010859),0-30,-118.292543
2,08/15/2018,FA0011237,DJ BIBINGKAHAN,DJ BIBINGKAHAN BAKESHOP,ACTIVE,1515 E AMAR RD,WEST COVINA,CA,91792,98,A,DAMPOJNY8,POINT (-117.913926 34.030964),0-30,-117.913926
4,09/07/2018,FA0252595,MEJICO GRILL AND TEQUILLA LOUNGE,MEJICO GRILL AND TEQUILLA LOUNGE,ACTIVE,29002 AGOURA RD,AGOURA HILLS,CA,91301,90,A,DAUEU4NGF,POINT (-118.756808 34.143452),151 +,-118.756808
5,09/18/2018,FA0158101,MCDONALD'S #10681,MCDONALD'S #10681,ACTIVE,5725 FLORENCE AVE,BELL GARDENS,CA,90201,91,A,DARQIUA45,POINT (-118.163665 33.967791),61-150,-118.163665

In [17]:
# Merge 'LNG' into Inspections DF
inspections_df = inspections_df.merge(lng, left_index = True, right_index = True)
inspections_df.head()

,ACTIVITY DATE,FACILITY ID,FACILITY NAME,PROGRAM NAME,PROGRAM STATUS,FACILITY ADDRESS,FACILITY CITY,FACILITY STATE,FACILITY ZIP,SCORE,GRADE,SERIAL NUMBER,Location,SEATS,LAT,LNG
0,09/10/2018,FA0242046,SERVERY- NICKELODEON,SERVERY- NICKELODEON,ACTIVE,203 W OLIVE AVE # C,BURBANK,CA,91502,96,A,DARRFUZBW,POINT (-118.314661 34.175253),31-60,-118.314661,34.175253
1,07/19/2018,FA0252769,TOMS JR BURGERS,TOMS JR BURGERS,ACTIVE,1030 W MARTIN LUTHER KING JR BLVD STE 108,LOS ANGELES,CA,90037-1867,98,A,DA0XQVMTN,POINT (-118.292543 34.010859),0-30,-118.292543,34.010859
2,08/15/2018,FA0011237,DJ BIBINGKAHAN,DJ BIBINGKAHAN BAKESHOP,ACTIVE,1515 E AMAR RD,WEST COVINA,CA,91792,98,A,DAMPOJNY8,POINT (-117.913926 34.030964),0-30,-117.913926,34.030964
4,09/07/2018,FA0252595,MEJICO GRILL AND TEQUILLA LOUNGE,MEJICO GRILL AND TEQUILLA LOUNGE,ACTIVE,29002 AGOURA RD,AGOURA HILLS,CA,91301,90,A,DAUEU4NGF,POINT (-118.756808 34.143452),151 +,-118.756808,34.143452
5,09/18/2018,FA0158101,MCDONALD'S #10681,MCDONALD'S #10681,ACTIVE,5725 FLORENCE AVE,BELL GARDENS,CA,90201,91,A,DARQIUA45,POINT (-118.163665 33.967791),61-150,-118.163665,33.967791

In [18]:
# Drop 'Location' column
clean_inspections_df = inspections_df.drop(columns = ["Location"])
clean_inspections_df.head()

,ACTIVITY DATE,FACILITY ID,FACILITY NAME,PROGRAM NAME,PROGRAM STATUS,FACILITY ADDRESS,FACILITY CITY,FACILITY STATE,FACILITY ZIP,SCORE,GRADE,SERIAL NUMBER,SEATS,LAT,LNG
0,09/10/2018,FA0242046,SERVERY- NICKELODEON,SERVERY- NICKELODEON,ACTIVE,203 W OLIVE AVE # C,BURBANK,CA,91502,96,A,DARRFUZBW,31-60,-118.314661,34.175253
1,07/19/2018,FA0252769,TOMS JR BURGERS,TOMS JR BURGERS,ACTIVE,1030 W MARTIN LUTHER KING JR BLVD STE 108,LOS ANGELES,CA,90037-1867,98,A,DA0XQVMTN,0-30,-118.292543,34.010859
2,08/15/2018,FA0011237,DJ BIBINGKAHAN,DJ BIBINGKAHAN BAKESHOP,ACTIVE,1515 E AMAR RD,WEST COVINA,CA,91792,98,A,DAMPOJNY8,0-30,-117.913926,34.030964
4,09/07/2018,FA0252595,MEJICO GRILL AND TEQUILLA LOUNGE,MEJICO GRILL AND TEQUILLA LOUNGE,ACTIVE,29002 AGOURA RD,AGOURA HILLS,CA,91301,90,A,DAUEU4NGF,151 +,-118.756808,34.143452
5,09/18/2018,FA0158101,MCDONALD'S #10681,MCDONALD'S #10681,ACTIVE,5725 FLORENCE AVE,BELL GARDENS,CA,90201,91,A,DARQIUA45,61-150,-118.163665,33.967791

#### Clean 'Facility Zip' data to show 5-digits only

In [19]:
def clean_zip(x):
    return x[:5]

clean_inspections_df['FACILITY ZIP'] = clean_inspections_df['FACILITY ZIP'].apply(clean_zip)

# Dislay DF
clean_inspections_df.head()

,ACTIVITY DATE,FACILITY ID,FACILITY NAME,PROGRAM NAME,PROGRAM STATUS,FACILITY ADDRESS,FACILITY CITY,FACILITY STATE,FACILITY ZIP,SCORE,GRADE,SERIAL NUMBER,SEATS,LAT,LNG
0,09/10/2018,FA0242046,SERVERY- NICKELODEON,SERVERY- NICKELODEON,ACTIVE,203 W OLIVE AVE # C,BURBANK,CA,91502,96,A,DARRFUZBW,31-60,-118.314661,34.175253
1,07/19/2018,FA0252769,TOMS JR BURGERS,TOMS JR BURGERS,ACTIVE,1030 W MARTIN LUTHER KING JR BLVD STE 108,LOS ANGELES,CA,90037,98,A,DA0XQVMTN,0-30,-118.292543,34.010859
2,08/15/2018,FA0011237,DJ BIBINGKAHAN,DJ BIBINGKAHAN BAKESHOP,ACTIVE,1515 E AMAR RD,WEST COVINA,CA,91792,98,A,DAMPOJNY8,0-30,-117.913926,34.030964
4,09/07/2018,FA0252595,MEJICO GRILL AND TEQUILLA LOUNGE,MEJICO GRILL AND TEQUILLA LOUNGE,ACTIVE,29002 AGOURA RD,AGOURA HILLS,CA,91301,90,A,DAUEU4NGF,151 +,-118.756808,34.143452
5,09/18/2018,FA0158101,MCDONALD'S #10681,MCDONALD'S #10681,ACTIVE,5725 FLORENCE AVE,BELL GARDENS,CA,90201,91,A,DARQIUA45,61-150,-118.163665,33.967791

In [20]:
# Check null values
for column in clean_inspections_df.columns:
    print(f"Column {column} has {clean_inspections_df[column].isnull().sum()} null values.")

Column ACTIVITY DATE has 0 null values.
Column FACILITY ID has 0 null values.
Column FACILITY NAME has 0 null values.
Column PROGRAM NAME has 0 null values.
Column PROGRAM STATUS has 0 null values.
Column FACILITY ADDRESS has 0 null values.
Column FACILITY CITY has 0 null values.
Column FACILITY STATE has 0 null values.
Column FACILITY ZIP has 0 null values.
Column SCORE has 0 null values.
Column GRADE has 68 null values.
Column SERIAL NUMBER has 0 null values.
Column SEATS has 0 null values.
Column LAT has 5889 null values.
Column LNG has 5889 null values.

In [21]:
# Drop null values
revised_clean_inspections_df = clean_inspections_df.dropna()
revised_clean_inspections_df.head()

,ACTIVITY DATE,FACILITY ID,FACILITY NAME,PROGRAM NAME,PROGRAM STATUS,FACILITY ADDRESS,FACILITY CITY,FACILITY STATE,FACILITY ZIP,SCORE,GRADE,SERIAL NUMBER,SEATS,LAT,LNG
0,09/10/2018,FA0242046,SERVERY- NICKELODEON,SERVERY- NICKELODEON,ACTIVE,203 W OLIVE AVE # C,BURBANK,CA,91502,96,A,DARRFUZBW,31-60,-118.314661,34.175253
1,07/19/2018,FA0252769,TOMS JR BURGERS,TOMS JR BURGERS,ACTIVE,1030 W MARTIN LUTHER KING JR BLVD STE 108,LOS ANGELES,CA,90037,98,A,DA0XQVMTN,0-30,-118.292543,34.010859
2,08/15/2018,FA0011237,DJ BIBINGKAHAN,DJ BIBINGKAHAN BAKESHOP,ACTIVE,1515 E AMAR RD,WEST COVINA,CA,91792,98,A,DAMPOJNY8,0-30,-117.913926,34.030964
4,09/07/2018,FA0252595,MEJICO GRILL AND TEQUILLA LOUNGE,MEJICO GRILL AND TEQUILLA LOUNGE,ACTIVE,29002 AGOURA RD,AGOURA HILLS,CA,91301,90,A,DAUEU4NGF,151 +,-118.756808,34.143452
5,09/18/2018,FA0158101,MCDONALD'S #10681,MCDONALD'S #10681,ACTIVE,5725 FLORENCE AVE,BELL GARDENS,CA,90201,91,A,DARQIUA45,61-150,-118.163665,33.967791

In [22]:
# Check #2 for null values
for column in revised_clean_inspections_df.columns:
    print(f"Column {column} has {revised_clean_inspections_df[column].isnull().sum()} null values.")

Column ACTIVITY DATE has 0 null values.
Column FACILITY ID has 0 null values.
Column FACILITY NAME has 0 null values.
Column PROGRAM NAME has 0 null values.
Column PROGRAM STATUS has 0 null values.
Column FACILITY ADDRESS has 0 null values.
Column FACILITY CITY has 0 null values.
Column FACILITY STATE has 0 null values.
Column FACILITY ZIP has 0 null values.
Column SCORE has 0 null values.
Column GRADE has 0 null values.
Column SERIAL NUMBER has 0 null values.
Column SEATS has 0 null values.
Column LAT has 0 null values.
Column LNG has 0 null values.

In [23]:
# Rename columns to replace 'space' with '_'
revised2_clean_inspect = revised_clean_inspections_df.rename(columns = {"ACTIVITY DATE" : "ACTIVITY_DATE",
                                                                        "FACILITY ID" : "FACILITY_ID",
                                                                        "FACILITY NAME" : "FACILITY_NAME",
                                                                        "PROGRAM NAME" : "PROGRAM_NAME",
                                                                        "PROGRAM STATUS" : "PROGRAM_STATUS",
                                                                        "FACILITY ADDRESS" : "FACILITY_ADDRESS",
                                                                        "FACILITY CITY" : "FACILITY_CITY",
                                                                        "FACILITY STATE" : "FACILITY_STATE",
                                                                        "FACILITY ZIP" : "FACILITY_ZIP",
                                                                        "SERIAL NUMBER" : "SERIAL_NUMBER"})

# Display DF
revised2_clean_inspect.head()

,ACTIVITY_DATE,FACILITY_ID,FACILITY_NAME,PROGRAM_NAME,PROGRAM_STATUS,FACILITY_ADDRESS,FACILITY_CITY,FACILITY_STATE,FACILITY_ZIP,SCORE,GRADE,SERIAL_NUMBER,SEATS,LAT,LNG
0,09/10/2018,FA0242046,SERVERY- NICKELODEON,SERVERY- NICKELODEON,ACTIVE,203 W OLIVE AVE # C,BURBANK,CA,91502,96,A,DARRFUZBW,31-60,-118.314661,34.175253
1,07/19/2018,FA0252769,TOMS JR BURGERS,TOMS JR BURGERS,ACTIVE,1030 W MARTIN LUTHER KING JR BLVD STE 108,LOS ANGELES,CA,90037,98,A,DA0XQVMTN,0-30,-118.292543,34.010859
2,08/15/2018,FA0011237,DJ BIBINGKAHAN,DJ BIBINGKAHAN BAKESHOP,ACTIVE,1515 E AMAR RD,WEST COVINA,CA,91792,98,A,DAMPOJNY8,0-30,-117.913926,34.030964
4,09/07/2018,FA0252595,MEJICO GRILL AND TEQUILLA LOUNGE,MEJICO GRILL AND TEQUILLA LOUNGE,ACTIVE,29002 AGOURA RD,AGOURA HILLS,CA,91301,90,A,DAUEU4NGF,151 +,-118.756808,34.143452
5,09/18/2018,FA0158101,MCDONALD'S #10681,MCDONALD'S #10681,ACTIVE,5725 FLORENCE AVE,BELL GARDENS,CA,90201,91,A,DARQIUA45,61-150,-118.163665,33.967791

In [24]:
# Check data types
for column in revised2_clean_inspect.columns:
    print(f"Column {column} has data type -- {revised2_clean_inspect[column].dtype}.")

Column ACTIVITY_DATE has data type -- object.
Column FACILITY_ID has data type -- object.
Column FACILITY_NAME has data type -- object.
Column PROGRAM_NAME has data type -- object.
Column PROGRAM_STATUS has data type -- object.
Column FACILITY_ADDRESS has data type -- object.
Column FACILITY_CITY has data type -- object.
Column FACILITY_STATE has data type -- object.
Column FACILITY_ZIP has data type -- object.
Column SCORE has data type -- int64.
Column GRADE has data type -- object.
Column SERIAL_NUMBER has data type -- object.
Column SEATS has data type -- object.
Column LAT has data type -- object.
Column LNG has data type -- object.

In [25]:
# Change select column(s) to string
revised2_clean_inspect[["FACILITY_ID", 
                       "FACILITY_NAME", 
                       "PROGRAM_NAME", 
                       "PROGRAM_STATUS", 
                       "FACILITY_ADDRESS", 
                       "FACILITY_CITY", 
                       "FACILITY_STATE", 
                       "FACILITY_ZIP", 
                       "GRADE", 
                       "SERIAL_NUMBER", 
                       "SEATS"]] = revised2_clean_inspect[["FACILITY_ID", 
                                                           "FACILITY_NAME", 
                                                           "PROGRAM_NAME", 
                                                           "PROGRAM_STATUS", 
                                                           "FACILITY_ADDRESS", 
                                                           "FACILITY_CITY", 
                                                           "FACILITY_STATE", 
                                                           "FACILITY_ZIP", 
                                                           "GRADE", 
                                                           "SERIAL_NUMBER", 
                                                           "SEATS"]].astype(str)

# Check data types
revised2_clean_inspect.dtypes

ACTIVITY_DATE       object
FACILITY_ID         object
FACILITY_NAME       object
PROGRAM_NAME        object
PROGRAM_STATUS      object
FACILITY_ADDRESS    object
FACILITY_CITY       object
FACILITY_STATE      object
FACILITY_ZIP        object
SCORE                int64
GRADE               object
SERIAL_NUMBER       object
SEATS               object
LAT                 object
LNG                 object
dtype: object

In [26]:
# Change select column(s) to interger
revised2_clean_inspect[["LAT", "LNG"]] = revised2_clean_inspect[["LAT", "LNG"]].astype(float)

# Check data types
revised2_clean_inspect.dtypes

ACTIVITY_DATE        object
FACILITY_ID          object
FACILITY_NAME        object
PROGRAM_NAME         object
PROGRAM_STATUS       object
FACILITY_ADDRESS     object
FACILITY_CITY        object
FACILITY_STATE       object
FACILITY_ZIP         object
SCORE                 int64
GRADE                object
SERIAL_NUMBER        object
SEATS                object
LAT                 float64
LNG                 float64
dtype: object

In [27]:
# Change select column(s) to datetime
revised2_clean_inspect["ACTIVITY_DATE"] = pd.to_datetime(revised2_clean_inspect["ACTIVITY_DATE"])

# Check data types
revised2_clean_inspect.dtypes

ACTIVITY_DATE       datetime64[ns]
FACILITY_ID                 object
FACILITY_NAME               object
PROGRAM_NAME                object
PROGRAM_STATUS              object
FACILITY_ADDRESS            object
FACILITY_CITY               object
FACILITY_STATE              object
FACILITY_ZIP                object
SCORE                        int64
GRADE                       object
SERIAL_NUMBER               object
SEATS                       object
LAT                        float64
LNG                        float64
dtype: object

In [28]:
# Display DF
revised2_clean_inspect.head()

,ACTIVITY_DATE,FACILITY_ID,FACILITY_NAME,PROGRAM_NAME,PROGRAM_STATUS,FACILITY_ADDRESS,FACILITY_CITY,FACILITY_STATE,FACILITY_ZIP,SCORE,GRADE,SERIAL_NUMBER,SEATS,LAT,LNG
0,2018-09-10,FA0242046,SERVERY- NICKELODEON,SERVERY- NICKELODEON,ACTIVE,203 W OLIVE AVE # C,BURBANK,CA,91502,96,A,DARRFUZBW,31-60,-118.314661,34.175253
1,2018-07-19,FA0252769,TOMS JR BURGERS,TOMS JR BURGERS,ACTIVE,1030 W MARTIN LUTHER KING JR BLVD STE 108,LOS ANGELES,CA,90037,98,A,DA0XQVMTN,0-30,-118.292543,34.010859
2,2018-08-15,FA0011237,DJ BIBINGKAHAN,DJ BIBINGKAHAN BAKESHOP,ACTIVE,1515 E AMAR RD,WEST COVINA,CA,91792,98,A,DAMPOJNY8,0-30,-117.913926,34.030964
4,2018-09-07,FA0252595,MEJICO GRILL AND TEQUILLA LOUNGE,MEJICO GRILL AND TEQUILLA LOUNGE,ACTIVE,29002 AGOURA RD,AGOURA HILLS,CA,91301,90,A,DAUEU4NGF,151 +,-118.756808,34.143452
5,2018-09-18,FA0158101,MCDONALD'S #10681,MCDONALD'S #10681,ACTIVE,5725 FLORENCE AVE,BELL GARDENS,CA,90201,91,A,DARQIUA45,61-150,-118.163665,33.967791

In [29]:
# Check shape
revised2_clean_inspect.shape

(165906, 15)

In [30]:
# Export to csv
revised2_clean_inspect.to_csv("./Resources/Clean/clean_inspections.csv")

### VIOLATIONS_DF DATA CLEANUP:

In [31]:
# Display DF
violations_df.head()

,SERIAL NUMBER,VIOLATION STATUS,VIOLATION CODE,VIOLATION DESCRIPTION,POINTS
0,DA000211Z,OUT OF COMPLIANCE,F006,# 06. Adequate handwashing facilities supplied...,2.0
1,DA000211Z,OUT OF COMPLIANCE,F044,"# 44. Floors, walls and ceilings: properly bui...",1.0
2,DA000211Z,OUT OF COMPLIANCE,F014,# 14. Food contact surfaces: clean and sanitized,2.0
3,DA000211Z,OUT OF COMPLIANCE,F029,"# 29. Toxic substances properly identified, st...",1.0
4,DA000211Z,OUT OF COMPLIANCE,F035,# 35. Equipment/Utensils - approved; installed...,1.0

In [32]:
# Check data types
violations_df.dtypes

SERIAL NUMBER             object
VIOLATION  STATUS         object
VIOLATION CODE            object
VIOLATION DESCRIPTION     object
POINTS                   float64
dtype: object

In [33]:
# Change all columns, but 'POINTS' to string
violations_df[["SERIAL NUMBER", 
               "VIOLATION  STATUS", 
               "VIOLATION CODE", 
               "VIOLATION DESCRIPTION"]] = violations_df[["SERIAL NUMBER", 
                                                          "VIOLATION  STATUS", 
                                                          "VIOLATION CODE", 
                                                          "VIOLATION DESCRIPTION"]].astype(str)

# Check data types
violations_df.dtypes

SERIAL NUMBER             object
VIOLATION  STATUS         object
VIOLATION CODE            object
VIOLATION DESCRIPTION     object
POINTS                   float64
dtype: object

In [34]:
# Rename columns to replace 'space' with '_'
clean_violations_df = violations_df.rename(columns = {"SERIAL NUMBER": "SERIAL_NUMER", 
                                                      "VIOLATION  STATUS": "VIOLATION_STATUS", 
                                                      "VIOLATION CODE": "VIOLATION_CODE", 
                                                      "VIOLATION DESCRIPTION": "VIOLATION_DESCRIPTION"})

# Display DF
clean_violations_df.head()

,SERIAL_NUMER,VIOLATION_STATUS,VIOLATION_CODE,VIOLATION_DESCRIPTION,POINTS
0,DA000211Z,OUT OF COMPLIANCE,F006,# 06. Adequate handwashing facilities supplied...,2.0
1,DA000211Z,OUT OF COMPLIANCE,F044,"# 44. Floors, walls and ceilings: properly bui...",1.0
2,DA000211Z,OUT OF COMPLIANCE,F014,# 14. Food contact surfaces: clean and sanitized,2.0
3,DA000211Z,OUT OF COMPLIANCE,F029,"# 29. Toxic substances properly identified, st...",1.0
4,DA000211Z,OUT OF COMPLIANCE,F035,# 35. Equipment/Utensils - approved; installed...,1.0

In [35]:
# Check for null values
for column in clean_violations_df.columns:
    print(f"Column {column} has {clean_violations_df[column].isnull().sum()} null values.")

Column SERIAL_NUMER has 0 null values.
Column VIOLATION_STATUS has 0 null values.
Column VIOLATION_CODE has 0 null values.
Column VIOLATION_DESCRIPTION has 0 null values.
Column POINTS has 0 null values.

In [36]:
# Check data shape
clean_violations_df.shape

(971331, 5)

In [37]:
# Export to csv
clean_violations_df.to_csv("./Resources/Clean/clean_violations.csv")

### COMMUNITY_HEALTH_DF DATA CLEANUP:

In [38]:
# Display DF
community_health_df.head()

,GEONAME,Pop_Tot,Prop_18y,Prop_64y,Prop_65y+,Prop_Blk,Prop_Lat,Prop_Whi,Prop_Asi,Prop_Ami,Prop_NHO,Prop_FPL1,Prop_FPL2,Prop_forb,Prop_Eng,LE,Prop_prsc,Prop_3rdg,Prop_edLH,Prop_edHG,Prop_edSC,Prop_edCG,MHI,No_libr,Prop_empl,Prop_emsu,Prop_vote,Rte_resp,Prop_PA,Prop_groc,Prop_60mi,No_farm,No_EBT,Prop_foin,No_CalF,Rte_CalF,Prop_FRPM,Prop_obse,Prop_DM,Rte_coin,Rte_brin,Prop_smok,Rte_luca,Rte_COPD,Rte_CVD,Prop_hbu1,Prop_hbu2,Prop_ownr,Prop_rentr,No_hless,Prop_asth,Rte_crim,Rte_hom,Rte_alco,Propt_envi,No_gasw,Rte_te17,Rte_te19,Prop_LBW,Rte_IMR,Prop_1stt,Prop_depr,Rte_suic,Rte_UOD,Rte_syin,Rte_goin,Rte_hiv,Prop_uinC,Prop_uinA,Prop_duinC,Prop_duinA,Propt_HPI,Rte_mein,Rte_cein,Rte_luin,Prop_fru,Prop_bev,Prop_hyp,Prop_marj,Prop_HI,Prop_grad,Prop_trua
0,Alhambra,86705,0.1831,0.6504,0.1665,0.0133,0.3435,0.0913,0.5498,0.0014,0.0007,0.1303,0.3356,0.5021,0.2112,84.55,0.665,0.5353,0.1934,0.2280,0.2497,0.3289,53582,1.0,0.940,0.3850,0.6235,0.7706,0.2731,0.5239,0.111,1,1,**,"15,799",0.3300,0.6598,0.1358,0.1040,45.7963,125.9019,0.1272,25.4872,21.7535,170.914,0.447,0.232,0.404,0.596,64,0.0449,168,**,12,6,2,2.1042,9.1180,0.0815,3.1022,0.8614,0.0523,7,3,14,66,208,0.0598,0.2070,0.0929,0.2291,43.3,**,**,34.6,0.2,0.2,0.2,0.1,0.0,1.0,0.1
1,Altadena,42525,0.2072,0.6221,0.1707,0.2374,0.2905,0.4129,0.0553,0.0019,0.0020,0.0988,0.2281,0.2021,0.0379,82.11,0.740,0.3942,0.1050,0.1397,0.2918,0.4635,86050,2.0,0.920,0.7335,0.7360,1.0975,0.3482,0.4524,0.120,1,1,**,-,-,0.5590,0.2441,0.1358,38.3670,189.2143,0.1129,25.2189,28.4887,211.035,0.401,0.193,0.719,0.281,58,0.0915,162,**,6,62,0,3.9610,7.6173,0.0703,**,0.8859,0.1099,10,8,19,119,330,0.0333,0.1745,0.0660,0.0924,75.5,33.8,**,35.3,0.1,0.3,0.3,0.2,0.1,0.9,0.4
2,Arcadia,56992,0.1794,0.6389,0.1817,0.0115,0.1250,0.2304,0.6315,0.0014,0.0003,0.0774,0.2042,0.4877,0.1888,85.42,0.675,0.7927,0.0789,0.1601,0.2430,0.5180,79934,1.0,0.941,0.5691,0.6271,1.9654,0.2662,0.5110,0.131,0,0,**,"6,638",0.1800,0.2066,0.0570,0.0819,32.9547,145.2497,0.1285,22.5416,22.0580,173.371,0.402,0.214,0.596,0.404,12,**,146,**,19,27,2,**,**,0.0590,**,0.8588,0.0493,9,**,8,46,56,0.0564,0.1245,0.1232,0.1876,73.4,22.0,**,29.5,0.1,0.2,0.2,0.0,0.0,1.0,0.1
3,Azusa,49479,0.2507,0.6538,0.0956,0.0292,0.6838,0.1938,0.0895,0.0024,0.0013,0.1636,0.3935,0.3082,0.1156,81.16,0.439,0.3390,0.2232,0.2932,0.2873,0.1962,53135,1.0,0.927,0.6201,0.6569,1.0168,0.3759,0.5997,0.121,0,0,0.2006,"8,868",0.5800,0.8060,0.2607,0.1198,31.3309,134.9485,0.1174,34.8652,33.1891,218.754,0.474,0.240,0.527,0.473,55,0.0660,354,6,14,48,0,3.5084,9.2802,0.0681,**,0.8810,0.0895,8,**,27,116,196,0.0708,0.2404,0.1117,0.1918,34.2,**,**,29.7,0.1,0.4,0.2,0.1,0.0,0.9,0.0
4,Baldwin Park,74438,0.2623,0.6330,0.1047,0.0099,0.7934,0.0432,0.1514,0.0012,0.0008,0.1591,0.4116,0.4453,0.1908,82.99,0.470,0.3227,0.3740,0.3170,0.1962,0.1128,51742,1.0,0.898,0.5712,0.6318,0.3406,0.3164,0.5444,0.125,1,1,0.2531,"14,206",0.7400,0.8729,0.2652,0.1307,43.8584,110.0378,0.1045,28.2446,31.2708,195.522,0.498,0.227,0.572,0.428,111,0.0904,391,5,10,9,0,7.3997,20.1220,0.0856,4.1881,0.8827,0.0544,**,5,21,98,171,0.0582,0.3259,0.0704,0.1874,22.3,**,**,26.5,0.1,0.4,0.3,0.1,0.0,1.0,0.4

In [39]:
# Capitalize "GEONAME" values
community_health_df["GEONAME"] = community_health_df["GEONAME"].str.upper()
community_health_df.head()

,GEONAME,Pop_Tot,Prop_18y,Prop_64y,Prop_65y+,Prop_Blk,Prop_Lat,Prop_Whi,Prop_Asi,Prop_Ami,Prop_NHO,Prop_FPL1,Prop_FPL2,Prop_forb,Prop_Eng,LE,Prop_prsc,Prop_3rdg,Prop_edLH,Prop_edHG,Prop_edSC,Prop_edCG,MHI,No_libr,Prop_empl,Prop_emsu,Prop_vote,Rte_resp,Prop_PA,Prop_groc,Prop_60mi,No_farm,No_EBT,Prop_foin,No_CalF,Rte_CalF,Prop_FRPM,Prop_obse,Prop_DM,Rte_coin,Rte_brin,Prop_smok,Rte_luca,Rte_COPD,Rte_CVD,Prop_hbu1,Prop_hbu2,Prop_ownr,Prop_rentr,No_hless,Prop_asth,Rte_crim,Rte_hom,Rte_alco,Propt_envi,No_gasw,Rte_te17,Rte_te19,Prop_LBW,Rte_IMR,Prop_1stt,Prop_depr,Rte_suic,Rte_UOD,Rte_syin,Rte_goin,Rte_hiv,Prop_uinC,Prop_uinA,Prop_duinC,Prop_duinA,Propt_HPI,Rte_mein,Rte_cein,Rte_luin,Prop_fru,Prop_bev,Prop_hyp,Prop_marj,Prop_HI,Prop_grad,Prop_trua
0,ALHAMBRA,86705,0.1831,0.6504,0.1665,0.0133,0.3435,0.0913,0.5498,0.0014,0.0007,0.1303,0.3356,0.5021,0.2112,84.55,0.665,0.5353,0.1934,0.2280,0.2497,0.3289,53582,1.0,0.940,0.3850,0.6235,0.7706,0.2731,0.5239,0.111,1,1,**,"15,799",0.3300,0.6598,0.1358,0.1040,45.7963,125.9019,0.1272,25.4872,21.7535,170.914,0.447,0.232,0.404,0.596,64,0.0449,168,**,12,6,2,2.1042,9.1180,0.0815,3.1022,0.8614,0.0523,7,3,14,66,208,0.0598,0.2070,0.0929,0.2291,43.3,**,**,34.6,0.2,0.2,0.2,0.1,0.0,1.0,0.1
1,ALTADENA,42525,0.2072,0.6221,0.1707,0.2374,0.2905,0.4129,0.0553,0.0019,0.0020,0.0988,0.2281,0.2021,0.0379,82.11,0.740,0.3942,0.1050,0.1397,0.2918,0.4635,86050,2.0,0.920,0.7335,0.7360,1.0975,0.3482,0.4524,0.120,1,1,**,-,-,0.5590,0.2441,0.1358,38.3670,189.2143,0.1129,25.2189,28.4887,211.035,0.401,0.193,0.719,0.281,58,0.0915,162,**,6,62,0,3.9610,7.6173,0.0703,**,0.8859,0.1099,10,8,19,119,330,0.0333,0.1745,0.0660,0.0924,75.5,33.8,**,35.3,0.1,0.3,0.3,0.2,0.1,0.9,0.4
2,ARCADIA,56992,0.1794,0.6389,0.1817,0.0115,0.1250,0.2304,0.6315,0.0014,0.0003,0.0774,0.2042,0.4877,0.1888,85.42,0.675,0.7927,0.0789,0.1601,0.2430,0.5180,79934,1.0,0.941,0.5691,0.6271,1.9654,0.2662,0.5110,0.131,0,0,**,"6,638",0.1800,0.2066,0.0570,0.0819,32.9547,145.2497,0.1285,22.5416,22.0580,173.371,0.402,0.214,0.596,0.404,12,**,146,**,19,27,2,**,**,0.0590,**,0.8588,0.0493,9,**,8,46,56,0.0564,0.1245,0.1232,0.1876,73.4,22.0,**,29.5,0.1,0.2,0.2,0.0,0.0,1.0,0.1
3,AZUSA,49479,0.2507,0.6538,0.0956,0.0292,0.6838,0.1938,0.0895,0.0024,0.0013,0.1636,0.3935,0.3082,0.1156,81.16,0.439,0.3390,0.2232,0.2932,0.2873,0.1962,53135,1.0,0.927,0.6201,0.6569,1.0168,0.3759,0.5997,0.121,0,0,0.2006,"8,868",0.5800,0.8060,0.2607,0.1198,31.3309,134.9485,0.1174,34.8652,33.1891,218.754,0.474,0.240,0.527,0.473,55,0.0660,354,6,14,48,0,3.5084,9.2802,0.0681,**,0.8810,0.0895,8,**,27,116,196,0.0708,0.2404,0.1117,0.1918,34.2,**,**,29.7,0.1,0.4,0.2,0.1,0.0,0.9,0.0
4,BALDWIN PARK,74438,0.2623,0.6330,0.1047,0.0099,0.7934,0.0432,0.1514,0.0012,0.0008,0.1591,0.4116,0.4453,0.1908,82.99,0.470,0.3227,0.3740,0.3170,0.1962,0.1128,51742,1.0,0.898,0.5712,0.6318,0.3406,0.3164,0.5444,0.125,1,1,0.2531,"14,206",0.7400,0.8729,0.2652,0.1307,43.8584,110.0378,0.1045,28.2446,31.2708,195.522,0.498,0.227,0.572,0.428,111,0.0904,391,5,10,9,0,7.3997,20.1220,0.0856,4.1881,0.8827,0.0544,**,5,21,98,171,0.0582,0.3259,0.0704,0.1874,22.3,**,**,26.5,0.1,0.4,0.3,0.1,0.0,1.0,0.4

In [40]:
# Drop columns as discussed
new_community_health_df = community_health_df.drop(columns = ["LE", 
                                                            "Prop_prsc", 
                                                            "Prop_3rdg", 
                                                            "No_libr", 
                                                            "Prop_empl", 
                                                            "Prop_emsu", 
                                                            "Prop_vote", 
                                                            "Rte_resp", 
                                                            "Prop_PA", 
                                                            "No_EBT", 
                                                            "No_CalF", 
                                                            "Rte_CalF", 
                                                            "Prop_FRPM", 
                                                            "Rte_coin", 
                                                            "Rte_brin", 
                                                            "Prop_smok", 
                                                            "Rte_luca", 
                                                            "Rte_COPD", 
                                                            "Prop_hbu1", 
                                                            "Prop_hbu2", 
                                                            "Prop_asth", 
                                                            "Rte_hom", 
                                                            "No_gasw", 
                                                            "Rte_te17", 
                                                            "Rte_te19", 
                                                            "Prop_LBW", 
                                                            "Rte_IMR", 
                                                            "Prop_1stt", 
                                                            "Rte_suic", 
                                                            "Rte_UOD", 
                                                            "Rte_syin", 
                                                            "Rte_goin", 
                                                            "Rte_hiv", 
                                                            "Prop_uinC", 
                                                            "Prop_uinA", 
                                                            "Prop_duinC", 
                                                            "Prop_duinA", 
                                                            "Rte_mein", 
                                                            "Rte_cein", 
                                                            "Rte_luin", 
                                                            "Prop_HI", 
                                                            "Prop_grad", 
                                                            "Prop_trua",
                                                            "Prop_foin"])

# Display DF
new_community_health_df.head()

,GEONAME,Pop_Tot,Prop_18y,Prop_64y,Prop_65y+,Prop_Blk,Prop_Lat,Prop_Whi,Prop_Asi,Prop_Ami,Prop_NHO,Prop_FPL1,Prop_FPL2,Prop_forb,Prop_Eng,Prop_edLH,Prop_edHG,Prop_edSC,Prop_edCG,MHI,Prop_groc,Prop_60mi,No_farm,Prop_obse,Prop_DM,Rte_CVD,Prop_ownr,Prop_rentr,No_hless,Rte_crim,Rte_alco,Propt_envi,Prop_depr,Propt_HPI,Prop_fru,Prop_bev,Prop_hyp,Prop_marj
0,ALHAMBRA,86705,0.1831,0.6504,0.1665,0.0133,0.3435,0.0913,0.5498,0.0014,0.0007,0.1303,0.3356,0.5021,0.2112,0.1934,0.2280,0.2497,0.3289,53582,0.5239,0.111,1,0.1358,0.1040,170.914,0.404,0.596,64,168,12,6,0.0523,43.3,0.2,0.2,0.2,0.1
1,ALTADENA,42525,0.2072,0.6221,0.1707,0.2374,0.2905,0.4129,0.0553,0.0019,0.0020,0.0988,0.2281,0.2021,0.0379,0.1050,0.1397,0.2918,0.4635,86050,0.4524,0.120,1,0.2441,0.1358,211.035,0.719,0.281,58,162,6,62,0.1099,75.5,0.1,0.3,0.3,0.2
2,ARCADIA,56992,0.1794,0.6389,0.1817,0.0115,0.1250,0.2304,0.6315,0.0014,0.0003,0.0774,0.2042,0.4877,0.1888,0.0789,0.1601,0.2430,0.5180,79934,0.5110,0.131,0,0.0570,0.0819,173.371,0.596,0.404,12,146,19,27,0.0493,73.4,0.1,0.2,0.2,0.0
3,AZUSA,49479,0.2507,0.6538,0.0956,0.0292,0.6838,0.1938,0.0895,0.0024,0.0013,0.1636,0.3935,0.3082,0.1156,0.2232,0.2932,0.2873,0.1962,53135,0.5997,0.121,0,0.2607,0.1198,218.754,0.527,0.473,55,354,14,48,0.0895,34.2,0.1,0.4,0.2,0.1
4,BALDWIN PARK,74438,0.2623,0.6330,0.1047,0.0099,0.7934,0.0432,0.1514,0.0012,0.0008,0.1591,0.4116,0.4453,0.1908,0.3740,0.3170,0.1962,0.1128,51742,0.5444,0.125,1,0.2652,0.1307,195.522,0.572,0.428,111,391,10,9,0.0544,22.3,0.1,0.4,0.3,0.1

In [61]:
# Replace '**' with '0' as discussed
new_community_health_df.replace('**', 0)

,GEONAME,Pop_Tot,Prop_18y,Prop_64y,Prop_65y+,Prop_Blk,Prop_Lat,Prop_Whi,Prop_Asi,Prop_Ami,Prop_NHO,Prop_FPL1,Prop_FPL2,Prop_forb,Prop_Eng,Prop_edLH,Prop_edHG,Prop_edSC,Prop_edCG,MHI,Prop_groc,Prop_60mi,No_farm,Prop_obse,Prop_DM,Rte_CVD,Prop_ownr,Prop_rentr,No_hless,Rte_crim,Rte_alco,Propt_envi,Prop_depr,Propt_HPI,Prop_fru,Prop_bev,Prop_hyp,Prop_marj
0,ALHAMBRA,86705,0.1831,0.6504,0.1665,0.0133,0.3435,0.0913,0.5498,0.0014,0.0007,0.1303,0.3356,0.5021,0.2112,0.1934,0.2280,0.2497,0.3289,53582,0.5239,0.111,1,0.1358,0.1040,170.9140,0.404,0.5960,64,168,12,6,0.0523,43.3,0.2,0.2,0.2,0.1
1,ALTADENA,42525,0.2072,0.6221,0.1707,0.2374,0.2905,0.4129,0.0553,0.0019,0.0020,0.0988,0.2281,0.2021,0.0379,0.1050,0.1397,0.2918,0.4635,86050,0.4524,0.120,1,0.2441,0.1358,211.0350,0.719,0.2810,58,162,6,62,0.1099,75.5,0.1,0.3,0.3,0.2
2,ARCADIA,56992,0.1794,0.6389,0.1817,0.0115,0.1250,0.2304,0.6315,0.0014,0.0003,0.0774,0.2042,0.4877,0.1888,0.0789,0.1601,0.2430,0.5180,79934,0.5110,0.131,0,0.0570,0.0819,173.3710,0.596,0.4040,12,146,19,27,0.0493,73.4,0.1,0.2,0.2,0.0
3,AZUSA,49479,0.2507,0.6538,0.0956,0.0292,0.6838,0.1938,0.0895,0.0024,0.0013,0.1636,0.3935,0.3082,0.1156,0.2232,0.2932,0.2873,0.1962,53135,0.5997,0.121,0,0.2607,0.1198,218.7540,0.527,0.4730,55,354,14,48,0.0895,34.2,0.1,0.4,0.2,0.1
4,BALDWIN PARK,74438,0.2623,0.6330,0.1047,0.0099,0.7934,0.0432,0.1514,0.0012,0.0008,0.1591,0.4116,0.4453,0.1908,0.3740,0.3170,0.1962,0.1128,51742,0.5444,0.125,1,0.2652,0.1307,195.5220,0.572,0.4280,111,391,10,9,0.0544,22.3,0.1,0.4,0.3,0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,WEST HOLLYWOOD,35797,0.0639,0.7801,0.1560,0.0310,0.1081,0.7984,0.0603,0.0014,0.0008,0.1403,0.2798,0.2587,0.1023,0.0456,0.0884,0.2404,0.6257,56317,0.9850,0.062,1,0.2207,0.0804,176.8870,0.201,0.7990,81,768,61,29,0.1503,70.6,0.4,0.2,0.2,0.2
83,WEST WHITTIER-LOS NIETOS,25441,0.2426,0.6253,0.1321,0.0080,0.8775,0.0954,0.0147,0.0032,0.0013,0.0912,0.2858,0.2691,0.0987,0.2858,0.3170,0.2711,0.1262,65363,0.4991,0.107,0,0.3584,0.1234,217.1750,0.721,0.2790,36,307,9,26,0.0791,41.2,0.1,0.4,0.2,0.1
84,WESTMONT,32835,0.2823,0.6208,0.0968,0.4945,0.4912,0.0096,0.0025,0.0012,0.0009,0.3546,0.6729,0.2324,0.1142,0.3041,0.2962,0.3272,0.0725,26808,0.1988,0.184,0,0.3195,0.1852,308.4830,0.306,0.6940,365,1514,7,69,0.0703,0.6,0.2,0.4,0.3,0.0
85,WHITTIER,88078,0.2304,0.6385,0.1311,0.0098,0.6750,0.2752,0.0361,0.0028,0.0011,0.1081,0.3274,0.1770,0.0542,0.1672,0.2376,0.3531,0.2421,66457,0.3930,0.125,1,0.2773,0.1291,199.0170,0.569,0.4310,258,293,16,63,0.0756,53.8,0.2,0.3,0.3,0.1
86,LOS ANGELES COUNTY,10227450,0.2253,0.6471,0.1276,0.0846,0.4876,0.2804,0.1431,0.0019,0.0024,0.1673,0.3766,0.3472,0.1374,0.2272,0.2068,0.2633,0.3027,56196,0.6185,0.125,-,0.2352,0.0983,204.8349,0.460,0.5403,46874,551,15,-,0.0861,-,0.1,0.4,0.2,0.1

In [62]:
new_community_health_df.loc[new_community_health_df['Prop_Eng'] == '**']

,GEONAME,Pop_Tot,Prop_18y,Prop_64y,Prop_65y+,Prop_Blk,Prop_Lat,Prop_Whi,Prop_Asi,Prop_Ami,Prop_NHO,Prop_FPL1,Prop_FPL2,Prop_forb,Prop_Eng,Prop_edLH,Prop_edHG,Prop_edSC,Prop_edCG,MHI,Prop_groc,Prop_60mi,No_farm,Prop_obse,Prop_DM,Rte_CVD,Prop_ownr,Prop_rentr,No_hless,Rte_crim,Rte_alco,Propt_envi,Prop_depr,Propt_HPI,Prop_fru,Prop_bev,Prop_hyp,Prop_marj
54,MANHATTAN BEACH,35170,0.2216,0.6243,0.1541,0.0086,0.0746,0.8182,0.096,0.0014,0.0013,0.0304,0.0652,0.1152,**,0.0216,0.0637,0.1792,0.7355,143527,0.6644,0.106,1,0.0857,0.0405,133.239,0.681,0.319,4,151,33,92,0.1697,98.6,0.2,0.2,0.3,0.1

In [65]:
new_community_health_df.loc[new_community_health_df['Prop_obse'] == '**']

,GEONAME,Pop_Tot,Prop_18y,Prop_64y,Prop_65y+,Prop_Blk,Prop_Lat,Prop_Whi,Prop_Asi,Prop_Ami,Prop_NHO,Prop_FPL1,Prop_FPL2,Prop_forb,Prop_Eng,Prop_edLH,Prop_edHG,Prop_edSC,Prop_edCG,MHI,Prop_groc,Prop_60mi,No_farm,Prop_obse,Prop_DM,Rte_CVD,Prop_ownr,Prop_rentr,No_hless,Rte_crim,Rte_alco,Propt_envi,Prop_depr,Propt_HPI,Prop_fru,Prop_bev,Prop_hyp,Prop_marj
8,BEVERLY HILLS,34652,0.1574,0.6406,0.2021,0.0209,0.0591,0.8212,0.0976,0.0009,0.0003,0.0801,0.1604,0.3841,0.1077,0.0505,0.128,0.2106,0.6109,97327,0.7074,0.049,1,**,**,138.562,0.412,0.588,16,306,46,43,0.1924,88.1,0.2,0.1,0.4,0.2

In [63]:
new = new_community_health_df.replace(to_replace = "**", value = 0)
new.sample(50)

,GEONAME,Pop_Tot,Prop_18y,Prop_64y,Prop_65y+,Prop_Blk,Prop_Lat,Prop_Whi,Prop_Asi,Prop_Ami,Prop_NHO,Prop_FPL1,Prop_FPL2,Prop_forb,Prop_Eng,Prop_edLH,Prop_edHG,Prop_edSC,Prop_edCG,MHI,Prop_groc,Prop_60mi,No_farm,Prop_obse,Prop_DM,Rte_CVD,Prop_ownr,Prop_rentr,No_hless,Rte_crim,Rte_alco,Propt_envi,Prop_depr,Propt_HPI,Prop_fru,Prop_bev,Prop_hyp,Prop_marj
35,LAWNDALE,33381,0.2474,0.6579,0.0946,0.1050,0.6036,0.1716,0.1053,0.0028,0.0117,0.1650,0.3355,0.3763,0.1510,0.2996,0.2482,0.2957,0.1565,47540,0.9450,0.078,1,0.2480,0.0980,198.2310,0.325,0.6750,43,581,14,78,0.0691,31.4,0.2,0.3,0.2,0.2
10,CALABASAS,24182,0.2031,0.6378,0.1591,0.0152,0.0662,0.8261,0.0911,0.0013,0.0002,0.0562,0.1255,0.2618,0.0360,0.0302,0.1202,0.2129,0.6367,106050,0.2029,0.206,1,0.1094,0,127.5160,0.702,0.2980,0,62,19,85,0.1412,91.6,0.1,0.2,0.2,0.1
51,LOS ANGELES COUNCIL DISTRICT 15,269467,0.2741,0.6188,0.1071,0.1272,0.6377,0.1634,0.0648,0.0022,0.0048,0.2472,0.4887,0.3177,0.1367,0.3079,0.2505,0.2733,0.1683,46423,0.5170,0.101,3,0.2736,0.1266,215.8852,0.399,0.6010,1773,697,12,66,0.0804,20.2,0.1,0.5,0.2,0.1
62,PASADENA,140883,0.2012,0.6477,0.1511,0.1034,0.3442,0.3919,0.1581,0.0015,0.0008,0.1306,0.2262,0.3037,0.0886,0.1257,0.1385,0.2354,0.5004,72402,0.5965,0.103,3,0.2233,0.0823,213.6960,0.436,0.5640,530,339,24,43,0.1247,66.4,0.2,0.3,0.3,0.1
60,PALMDALE,159690,0.2807,0.6328,0.0864,0.1545,0.5498,0.2498,0.0413,0.0031,0.0014,0.2018,0.4764,0.2624,0.1000,0.2583,0.2592,0.3341,0.1483,52392,0.2773,0.318,0,0.3054,0.1217,236.9120,0.632,0.3680,212,436,9,95,0.0964,24.4,0.1,0.4,0.3,0.1
58,MONTEREY PARK,61121,0.1724,0.6155,0.2121,0.0033,0.2743,0.0458,0.6754,0.0010,0.0003,0.1414,0.4133,0.5360,0.2847,0.2127,0.2443,0.2385,0.3044,54097,0.5435,0.086,1,0.1058,0.1222,145.1300,0.520,0.4800,7,214,14,4,0.0442,32.1,0.1,0.2,0.3,0.0
27,HAWTHORNE,87772,0.2627,0.6418,0.0954,0.2813,0.5288,0.1069,0.0687,0.0021,0.0123,0.1863,0.4591,0.3477,0.1339,0.2619,0.2454,0.3023,0.1904,44504,0.8672,0.109,0,0.2351,0.1182,244.0150,0.266,0.7340,100,745,11,69,0.0793,29.3,0.2,0.4,0.3,0.2
23,GARDENA,60677,0.2150,0.6208,0.1642,0.2395,0.3927,0.0911,0.2682,0.0016,0.0068,0.1401,0.2806,0.3372,0.1451,0.1818,0.2703,0.3161,0.2318,47674,0.7461,0.076,1,0.2770,0.0991,208.0340,0.512,0.4880,186,557,26,76,0.0584,41.9,0.1,0.5,0.3,0.1
1,ALTADENA,42525,0.2072,0.6221,0.1707,0.2374,0.2905,0.4129,0.0553,0.0019,0.0020,0.0988,0.2281,0.2021,0.0379,0.1050,0.1397,0.2918,0.4635,86050,0.4524,0.120,1,0.2441,0.1358,211.0350,0.719,0.2810,58,162,6,62,0.1099,75.5,0.1,0.3,0.3,0.2
12,CERRITOS,49250,0.1645,0.6091,0.2264,0.0696,0.1253,0.1562,0.6453,0.0011,0.0025,0.0398,0.0891,0.4471,0.1142,0.0831,0.1464,0.2886,0.4819,90321,0.6596,0.128,1,0.2342,0.0948,166.0200,0.791,0.2090,27,225,16,83,0.0410,79.7,0.1,0.3,0.2,0.0
75,SOUTH PASADENA,25937,0.1988,0.6509,0.1503,0.0279,0.1932,0.4332,0.3443,0.0011,0.0002,0.0646,0.1645,0.2663,0.0667,0.0455,0.1099,0.2542,0.5904,78957,0.6830,0.100,1,0.1306,0.0850,163.1610,0.435,0.5650,9,104,13,38,0.0857,87.4,0.2,0.2,0.3,0.1
44,LOS ANGELES COUNCIL DISTRICT 8,252296,0.2650,0.6320,0.1030,0.3996,0.5666,0.0177,0.0137,0.0016,0.0007,0.2890,0.5469,0.3198,0.1296,0.3587,0.2585,0.2705,0.1123,32922,0.5774,0.137,1,0.3187,0.1543,303.8390,0.373,0.6270,1497,1498,6,32,0.0604,2.0,0.1,0.5,0.3,0.1
49,LOS ANGELES COUNCIL DISTRICT 13,258882,0.1859,0.6971,0.1170,0.0322,0.5424,0.2376,0.1852,0.0017,0.0008,0.2297,0.4886,0.4957,0.2660,0.2635,0.1863,0.2354,0.3148,39448,0.8520,0.145,6,0.1869,0.1134,204.4620,0.140,0.8600,3036,718,22,3,0.0943,23.0,0.2,0.4,0.2,0.1
48,LOS ANGELES COUNCIL DISTRICT 12,271125,0.1845,0.6481,0.1673,0.0412,0.2835,0.4787,0.1938,0.0016,0.0012,0.0908,0.2290,0.3189,0.0754,0.0966,0.2028,0.2974,0.4031,80913,0.4766,0.149,2,0.2157,0.0696,201.0350,0.685,0.3150,906,284,12,36,0.0797,69.2,0.1,0.3,0.2,0.1
66,REDONDO BEACH,69316,0.2056,0.6614,0.1330,0.0272,0.1567,0.6806,0.1302,0.0025,0.0028,0.0462,0.0957,0.1877,0.0393,0.0415,0.1110,0.2785,0.5689,105145,0.7645,0.116,2,0.1971,0.0599,177.9619,0.499,0.5010,216,231,26,84,0.1129,93.0,0.2,0.2,0.2,0.1
29,INGLEWOOD,116361,0.2464,0.6390,0.1146,0.4279,0.5273,0.0272,0.0123,0.0019,0.0034,0.2066,0.3893,0.2782,0.1121,0.2747,0.2058,0.3375,0.1820,42044,0.6384,0.114,1,0.3211,0.1239,260.5470,0.351,0.6490,502,713,13,74,0.0746,27.2,0.2,0.5,0.3,0.2
74,SOUTH GATE,99741,0.2797,0.6295,0.0908,0.0068,0.9499,0.0344,0.0069,0.0012,0.0007,0.1953,0.5130,0.4315,0.2539,0.4763,0.2502,0.1977,0.0759,43552,0.7935,0.129,1,0.2791,0.1070,177.9680,0.453,0.5470,122,662,11,56,0.0600,16.0,0.1,0.5,0.2,0.1
40,LOS ANGELES COUNCIL DISTRICT 4,260788,0.1597,0.7003,0.1400,0.0456,0.1613,0.6310,0.1602,0.0013,0.0007,0.1024,0.2241,0.3071,0.0927,0.0580,0.1202,0.2333,0.5886,77274,0.6961,0.095,5,0.1515,0.0649,173.7520,0.340,0.6600,628,321,19,19,0.1239,72.0,0.2,0.2,0.2,0.2
38,LOS ANGELES COUNCIL DISTRICT 2,265068,0.2124,0.6708,0.1168,0.0406,0.4680,0.4194,0.0696,0.0015,0.0010,0.1749,0.3840,0.3859,0.1360,0.2008,0.2004,0.2619,0.3370,52281,0.6919,0.134,2,0.2078,0.0948,217.3220,0.338,0.6620,1084,389,14,13,0.1037,39.8,0.2,0.4,0.2,0.2
84,WESTMONT,32835,0.2823,0.6208,0.0968,0.4945,0.4912,0.0096,0.0025,0.0012,0.0009,0.3546,0.6729,0.2324,0.1142,0.3041,0.2962,0.3272,0.0725,26808,0.1988,0.184,0,0.3195,0.1852,308.4830,0.306,0.6940,365,1514,7,69,0.0703,0.6,0.2,0.4,0.3,0.0
70,SAN FERNANDO,24465,0.2703,0.6303,0.0993,0.0065,0.9286,0.0529,0.0085,0.0028,0.0007,0.2043,0.5118,0.3738,0.1772,0.4153,0.2641,0.2007,0.1198,55170,0.7416,0.098,0,0.2813,0.1114,189.2970,0.537,0.4630,24,540,16,24,0.0808,40.5,0.1,0.5,0.2,0.1
34,LANCASTER,156606,0.2697,0.6326,0.0977,0.2191,0.3872,0.3437,0.0439,0.0042,0.0019,0.2130,0.3965,0.1328,0.0549,0.1860,0.2940,0.3694,0.1506,47225,0.3111,0.200,1,0.2909,0.1321,294.1700,0.562,0.4380,1055,704,11,87,0.1271,19.5,0.2,0.3,0.3,0.2
16,CUDAHY,24526,0.3009,0.6292,0.0699,0.0096,0.9585,0.0245,0.0049,0.0022,0.0003,0.2996,0.7451,0.4631,0.3028,0.5712,0.2217,0.1607,0.0464,36429,0.8685,0.120,0,0.3199,0.1014,178.2500,0.162,0.8380,119,310,9,64,0.1121,11.1,0.2,0.6,0.2,0.1
25,GLENDORA,52231,0.1942,0.6430,0.1628,0.0164,0.3181,0.5811,0.0817,0.0019,0.0008,0.0784,0.1503,0.1653,0.0410,0.0985,0.1888,0.3878,0.3250,75148,0.4304,0.179,0,0.3262,0.1045,228.8290,0.689,0.3110,270,134,13,57,0.1060,68.5,0.1,0.2,0.3,0.1
2,ARCADIA,56992,0.1794,0.6389,0.1817,0.0115,0.1250,0.2304,0.6315,0.0014,0.0003,0.0774,0.2042,0.4877,0.1888,0.0789,0.1601,0.2430,0.5180,79934,0.5110,0.131,0,0.0570,0.0819,173.3710,0.596,0.4040,12,146,19,27,0.0493,73.4,0.1,0.2,0.2,0.0
37,LOS ANGELES COUNCIL DISTRICT 1,274628,0.2332,0.6540,0.1128,0.0276,0.7060,0.0829,0.1810,0.0017,0.0008,0.2981,0.6119,0.5229,0.3497,0.4296,0.2035,0.1746,0.1923,34896,0.8857,0.139,2,0.2164,0.1278,178.4320,0.182,0.8180,1986,667,12,6,0.0746,9.7,0.1,0.5,0.2,0.1
78,TORRANCE,146686,0.1949,0.6394,0.1658,0.0270,0.1698,0.4157,0.3821,0.0021,0.0033,0.0622,0.1291,0.2878,0.0988,0.0655,0.1737,0.3019,0.4589,79549,0.6409,0.098,2,0.1695,0.0792,184.7830,0.551,0.4490,107,176,20,90,0.0625,76.9,0.1,0.3,0.3,0.1
81,WEST COVINA,107688,0.2149,0.6373,0.1478,0.0408,0.5311,0.1464,0.2780,0.0022,0.0014,0.0913,0.2640,0.3437,0.1061,0.1690,0.2452,0.3207,0.2651,69189,0.4549,0.092,1,0.2751,0.1048,193.0430,0.729,0.2710,48,246,11,15,0.0558,57.3,0.1,0.4,0.3,0.1
28,HUNTINGTON PARK,59509,0.2832,0.6317,0.0852,0.0040,0.9713,0.0182,0.0058,0.0005,0.0002,0.2732,0.7259,0.4896,0.3153,0.5865,0.1939,0.1620,0.0576,34887,0.8284,0.122,1,0.2987,0.0924,198.1520,0.240,0.7600,83,778,16,52,0.0855,4.8,0.1,0.6,0.2,0.1
36,LONG BEACH,483509,0.2345,0.6538,0.1118,0.1385,0.4230,0.2873,0.1368,0.0029,0.0115,0.1959,0.4047,0.2597,0.0812,0.2063,0.1868,0.3149,0.2920,52783,0.7327,0.122,8,0.2422,0.1167,253.2930,0.402,0.5980,1863,589,18,66,0.0884,32.8,0.1,0.4,0.3,0.1
6,BELL GARDENS,42817,0.3026,0.6274,0.0700,0.0050,0.9584,0.0280,0.0055,0.0022,0.0008,0.2693,0.6934,0.4291,0.2324,0.5573,0.2447,0.1444,0.0536,37882,0.6476,0.088,0,0.2860,0.1225,213.8190,0.229,0.7710,104,362,14,53,0.0983,4.1,0.1,0.4,0.2,0.1
24,GLENDALE,201604,0.1690,0.6548,0.1762,0.0120,0.1755,0.6382,0.1727,0.0010,0.0005,0.1318,0.2943,0.5444,0.2522,0.1564,0.1908,0.2738,0.3790,52574,0.7505,0.098,1,0.1516,0.0716,181.4710,0.353,0.6470,240,113,17,1,0.0980,46.1,0.1,0.3,0.2,0.2
5,BELL,36595,0.2893,0.6249,0.0857,0.0061,0.9286,0.0569,0.0063,0.0020,0.0000,0.2588,0.6647,0.4271,0.2669,0.5260,0.2014,0.1999,0.0726,37269,0.8400,0.109,0,0.2578,0.1154,185.4260,0.276,0.7240,477,637,13,45,0.0755,10.4,0.1,0.4,0.2,0.1
71,SAN GABRIEL,40309,0.1883,0.6467,0.1649,0.0092,0.2587,0.1082,0.6220,0.0014,0.0006,0.1190,0.3259,0.5478,0.2580,0.2191,0.2533,0.2220,0.3057,51579,0.7339,0.093,0,0.0842,0.1167,177.6120,0.480,0.5200,9,243,24,31,0.0562,44.0,0.1,0.2,0.2,0.0
43,LOS ANGELES COUNCIL DISTRICT 7,278658,0.2538,0.6354,0.1108,0.0355,0.7098,0.1921,0.0599,0.0020,0.0007,0.1747,0.4355,0.3971,0.1369,0.3172,0.2586,0.2544,0.1697,57352,0.4932,0.125,1,0.2861,0.0981,222.0630,0.602,0.3980,1206,361,8,27,0.0687,30.7,0.1,0.5,0.2,0.1
46,LOS ANGELES COUNCIL DISTRICT 10,275480,0.2209,0.6597,0.1194,0.2543,0.4912,0.0877,0.1643,0.0017,0.0008,0.2257,0.4773,0.4216,0.2146,0.2609,0.2195,0.2513,0.2683,40218,0.8028,0.121,4,0.2276,0.1345,227.3250,0.239,0.7610,1112,759,18,13,0.0652,21.6,0.1,0.4,0.2,0.2
8,BEVERLY HILLS,34652,0.1574,0.6406,0.2021,0.0209,0.0591,0.8212,0.0976,0.0009,0.0003,0.0801,0.1604,0.3841,0.1077,0.0505,0.1280,0.2106,0.6109,97327,0.7074,0.049,1,0,0,138.5620,0.412,0.5880,16,306,46,43,0.1924,88.1,0.2,0.1,0.4,0.2
68,ROWLAND HEIGHTS,51206,0.1796,0.6448,0.1756,0.0137,0.2754,0.0974,0.6110,0.0008,0.0017,0.1048,0.3109,0.5630,0.2732,0.1556,0.2074,0.2744,0.3626,59534,0.4661,0.163,0,0.1848,0.1049,162.9190,0.670,0.3300,66,168,12,85,0.0422,44.7,0.1,0.3,0.2,0.0
52,"LOS ANGELES, CITY OF",4032993,0.2221,0.6574,0.1205,0.0912,0.5004,0.2888,0.1168,0.0017,0.0011,0.2031,0.4241,0.3820,0.1575,0.2453,0.1963,0.2387,0.3197,50205,0.6835,0.121,58,0.2193,0.1006,205.0990,0.368,0.6320,28464,620,15,21,0.0925,28.6,0.2,0.4,0.2,0.1
86,LOS ANGELES COUNTY,10227450,0.2253,0.6471,0.1276,0.0846,0.4876,0.2804,0.1431,0.0019,0.0024,0.1673,0.3766,0.3472,0.1374,0.2272,0.2068,0.2633,0.3027,56196,0.6185,0.125,-,0.2352,0.0983,204.8349,0.460,0.5403,46874,551,15,-,0.0861,-,0.1,0.4,0.2,0.1
56,MONROVIA,37467,0.2219,0.6383,0.1398,0.0657,0.3988,0.4106,0.1203,0.0023,0.0023,0.0986,0.2435,0.2526,0.0737,0.1120,0.1973,0.3252,0.3656,70358,0.6666,0.144,1,0.1778,0.1051,215.7250,0.487,0.5130,61,160,22,51,0.0966,67.1,0.2,0.3,0.2,0.1
17,CULVER CITY,40351,0.1871,0.6403,0.1726,0.0967,0.2358,0.5031,0.1605,0.0017,0.0022,0.0751,0.1395,0.2300,0.0498,0.0780,0.1146,0.2733,0.5341,81189,0.7078,0.054,0,0.2200,0.0735,199.1613,0.551,0.4490,122,528,38,44,0.1076,81.1,0.2,0.2,0.4,0.2
57,MONTEBELLO,63732,0.2361,0.6114,0.1525,0.0066,0.7986,0.0844,0.1081,0.0016,0.0008,0.1408,0.4130,0.3748,0.2185,0.2830,0.2912,0.2386,0.1872,45875,0.4436,0.182,0,0.2713,0.1048,198.0650,0.454,0.5460,52,336,14,52,0.0506,25.8,0.2,0.6,0.2,0.1
4,BALDWIN PARK,74438,0.2623,0.6330,0.1047,0.0099,0.7934,0.0432,0.1514,0.0012,0.0008,0.1591,0.4116,0.4453,0.1908,0.3740,0.3170,0.1962,0.1128,51742,0.5444,0.125,1,0.2652,0.1307,195.5220,0.572,0.4280,111,391,10,9,0.0544,22.3,0.1,0.4,0.3,0.1
82,WEST HOLLYWOOD,35797,0.0639,0.7801,0.1560,0.0310,0.1081,0.7984,0.0603,0.0014,0.0008,0.1403,0.2798,0.2587,0.1023,0.0456,0.0884,0.2404,0.6257,56317,0.9850,0.062,1,0.2207,0.0804,176.8870,0.201,0.7990,81,768,61,29,0.1503,70.6,0.4,0.2,0.2,0.2
45,LOS ANGELES COUNCIL DISTRICT 9,285373,0.2983,0.6397,0.0620,0.1512,0.7918,0.0319,0.0240,0.0009,0.0002,0.3869,0.7041,0.4335,0.2420,0.5521,0.2351,0.1532,0.0596,28614,0.8409,0.133,2,0.3259,0.1304,232.6090,0.267,0.7330,3458,1120,9,8,0.0800,0.0,0.1,0.5,0.2,0.1
22,FLORENCE-GRAHAM,65822,0.3145,0.6147,0.0708,0.0893,0.9012,0.0074,0.0011,0.0007,0.0002,0.3100,0.8009,0.4329,0.2654,0.5855,0.2333,0.1368,0.0444,33934,0.9701,0.133,0,0.3126,0.1116,234.9910,0.342,0.6580,543,801,13,37,0.0653,2.7,0.1,0.5,0.2,0.1
53,LYNWOOD,72189,0.2946,0.6337,0.0718,0.0996,0.8695,0.0217,0.0056,0.0011,0.0026,0.2306,0.5889,0.3896,0.1797,0.4723,0.2633,0.2043,0.0601,43109,0.5670,0.120,0,0.3225,0.1195,225.3870,0.435,0.5650,118,650,10,71,0.0620,13.9,0.1,0.4,0.2,0.1
13,CLAREMONT,36121,0.1511,0.6661,0.1828,0.0445,0.2041,0.6072,0.1409,0.0021,0.0010,0.0631,0.1195,0.1956,0.0462,0.0679,0.1059,0.2640,0.5622,88523,0.4345,0.139,1,0.2753,0.0920,204.4231,0.659,0.3410,27,163,18,1,0.1043,78.3,0.2,0.1,0.3,0.2
54,MANHATTAN BEACH,35170,0.2216,0.6243,0.1541,0.0086,0.0746,0.8182,0.0960,0.0014,0.0013,0.0304,0.0652,0.1152,0,0.0216,0.0637,0.1792,0.7355,143527,0.6644,0.106,1,0.0857,0.0405,133.2390,0.681,0.3190,4,151,33,92,0.1697,98.6,0.2,0.2,0.3,0.1

In [64]:
new.loc[new['Prop_Eng'] == '**']

Empty DataFrame
Columns: [GEONAME, Pop_Tot, Prop_18y, Prop_64y, Prop_65y+, Prop_Blk, Prop_Lat, Prop_Whi, Prop_Asi, Prop_Ami, Prop_NHO, Prop_FPL1, Prop_FPL2, Prop_forb, Prop_Eng, Prop_edLH, Prop_edHG, Prop_edSC, Prop_edCG, MHI, Prop_groc, Prop_60mi, No_farm, Prop_obse, Prop_DM, Rte_CVD, Prop_ownr, Prop_rentr, No_hless, Rte_crim, Rte_alco, Propt_envi, Prop_depr, Propt_HPI, Prop_fru, Prop_bev, Prop_hyp, Prop_marj]
Index: []

In [58]:
new.loc[new['Prop_obse'] == '**']

Empty DataFrame
Columns: [GEONAME, Pop_Tot, Prop_18y, Prop_64y, Prop_65y+, Prop_Blk, Prop_Lat, Prop_Whi, Prop_Asi, Prop_Ami, Prop_NHO, Prop_FPL1, Prop_FPL2, Prop_forb, Prop_Eng, Prop_edLH, Prop_edHG, Prop_edSC, Prop_edCG, MHI, Prop_groc, Prop_60mi, No_farm, Prop_obse, Prop_DM, Rte_CVD, Prop_ownr, Prop_rentr, No_hless, Rte_crim, Rte_alco, Propt_envi, Prop_depr, Propt_HPI, Prop_fru, Prop_bev, Prop_hyp, Prop_marj]
Index: []

In [60]:
new.loc[new['Prop_DM'] == "**"]

Empty DataFrame
Columns: [GEONAME, Pop_Tot, Prop_18y, Prop_64y, Prop_65y+, Prop_Blk, Prop_Lat, Prop_Whi, Prop_Asi, Prop_Ami, Prop_NHO, Prop_FPL1, Prop_FPL2, Prop_forb, Prop_Eng, Prop_edLH, Prop_edHG, Prop_edSC, Prop_edCG, MHI, Prop_groc, Prop_60mi, No_farm, Prop_obse, Prop_DM, Rte_CVD, Prop_ownr, Prop_rentr, No_hless, Rte_crim, Rte_alco, Propt_envi, Prop_depr, Propt_HPI, Prop_fru, Prop_bev, Prop_hyp, Prop_marj]
Index: []

In [43]:
# Replace '-' with '0' as discussed
new_community_health_df.replace('-', 0)

,GEONAME,Pop_Tot,Prop_18y,Prop_64y,Prop_65y+,Prop_Blk,Prop_Lat,Prop_Whi,Prop_Asi,Prop_Ami,Prop_NHO,Prop_FPL1,Prop_FPL2,Prop_forb,Prop_Eng,Prop_edLH,Prop_edHG,Prop_edSC,Prop_edCG,MHI,Prop_groc,Prop_60mi,No_farm,Prop_obse,Prop_DM,Rte_CVD,Prop_ownr,Prop_rentr,No_hless,Rte_crim,Rte_alco,Propt_envi,Prop_depr,Propt_HPI,Prop_fru,Prop_bev,Prop_hyp,Prop_marj
0,ALHAMBRA,86705,0.1831,0.6504,0.1665,0.0133,0.3435,0.0913,0.5498,0.0014,0.0007,0.1303,0.3356,0.5021,0.2112,0.1934,0.2280,0.2497,0.3289,53582,0.5239,0.111,1,0.1358,0.1040,170.9140,0.404,0.5960,64,168,12,6,0.0523,43.3,0.2,0.2,0.2,0.1
1,ALTADENA,42525,0.2072,0.6221,0.1707,0.2374,0.2905,0.4129,0.0553,0.0019,0.0020,0.0988,0.2281,0.2021,0.0379,0.1050,0.1397,0.2918,0.4635,86050,0.4524,0.120,1,0.2441,0.1358,211.0350,0.719,0.2810,58,162,6,62,0.1099,75.5,0.1,0.3,0.3,0.2
2,ARCADIA,56992,0.1794,0.6389,0.1817,0.0115,0.1250,0.2304,0.6315,0.0014,0.0003,0.0774,0.2042,0.4877,0.1888,0.0789,0.1601,0.2430,0.5180,79934,0.5110,0.131,0,0.0570,0.0819,173.3710,0.596,0.4040,12,146,19,27,0.0493,73.4,0.1,0.2,0.2,0.0
3,AZUSA,49479,0.2507,0.6538,0.0956,0.0292,0.6838,0.1938,0.0895,0.0024,0.0013,0.1636,0.3935,0.3082,0.1156,0.2232,0.2932,0.2873,0.1962,53135,0.5997,0.121,0,0.2607,0.1198,218.7540,0.527,0.4730,55,354,14,48,0.0895,34.2,0.1,0.4,0.2,0.1
4,BALDWIN PARK,74438,0.2623,0.6330,0.1047,0.0099,0.7934,0.0432,0.1514,0.0012,0.0008,0.1591,0.4116,0.4453,0.1908,0.3740,0.3170,0.1962,0.1128,51742,0.5444,0.125,1,0.2652,0.1307,195.5220,0.572,0.4280,111,391,10,9,0.0544,22.3,0.1,0.4,0.3,0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,WEST HOLLYWOOD,35797,0.0639,0.7801,0.1560,0.0310,0.1081,0.7984,0.0603,0.0014,0.0008,0.1403,0.2798,0.2587,0.1023,0.0456,0.0884,0.2404,0.6257,56317,0.9850,0.062,1,0.2207,0.0804,176.8870,0.201,0.7990,81,768,61,29,0.1503,70.6,0.4,0.2,0.2,0.2
83,WEST WHITTIER-LOS NIETOS,25441,0.2426,0.6253,0.1321,0.0080,0.8775,0.0954,0.0147,0.0032,0.0013,0.0912,0.2858,0.2691,0.0987,0.2858,0.3170,0.2711,0.1262,65363,0.4991,0.107,0,0.3584,0.1234,217.1750,0.721,0.2790,36,307,9,26,0.0791,41.2,0.1,0.4,0.2,0.1
84,WESTMONT,32835,0.2823,0.6208,0.0968,0.4945,0.4912,0.0096,0.0025,0.0012,0.0009,0.3546,0.6729,0.2324,0.1142,0.3041,0.2962,0.3272,0.0725,26808,0.1988,0.184,0,0.3195,0.1852,308.4830,0.306,0.6940,365,1514,7,69,0.0703,0.6,0.2,0.4,0.3,0.0
85,WHITTIER,88078,0.2304,0.6385,0.1311,0.0098,0.6750,0.2752,0.0361,0.0028,0.0011,0.1081,0.3274,0.1770,0.0542,0.1672,0.2376,0.3531,0.2421,66457,0.3930,0.125,1,0.2773,0.1291,199.0170,0.569,0.4310,258,293,16,63,0.0756,53.8,0.2,0.3,0.3,0.1
86,LOS ANGELES COUNTY,10227450,0.2253,0.6471,0.1276,0.0846,0.4876,0.2804,0.1431,0.0019,0.0024,0.1673,0.3766,0.3472,0.1374,0.2272,0.2068,0.2633,0.3027,56196,0.6185,0.125,0,0.2352,0.0983,204.8349,0.460,0.5403,46874,551,15,0,0.0861,0,0.1,0.4,0.2,0.1

In [44]:
# Check data types
for column in new_community_health_df.columns:
    print(f"Column {column} has data type -- {community_health_df[column].dtype}.")

Column GEONAME has data type -- object.
Column Pop_Tot has data type -- int64.
Column Prop_18y has data type -- float64.
Column Prop_64y has data type -- float64.
Column Prop_65y+ has data type -- float64.
Column Prop_Blk has data type -- float64.
Column Prop_Lat has data type -- float64.
Column Prop_Whi has data type -- float64.
Column Prop_Asi has data type -- float64.
Column Prop_Ami has data type -- float64.
Column Prop_NHO has data type -- float64.
Column Prop_FPL1 has data type -- float64.
Column Prop_FPL2 has data type -- float64.
Column Prop_forb has data type -- float64.
Column Prop_Eng has data type -- object.
Column Prop_edLH has data type -- float64.
Column Prop_edHG has data type -- float64.
Column Prop_edSC has data type -- float64.
Column Prop_edCG has data type -- float64.
Column MHI has data type -- int64.
Column Prop_groc has data type -- float64.
Column Prop_60mi has data type -- float64.
Column No_farm has data type -- object.
Column Prop_obse has data type -- object.
Column Prop_DM has data type -- object.
Column Rte_CVD has data type -- float64.
Column Prop_ownr has data type -- float64.
Column Prop_rentr has data type -- float64.
Column No_hless has data type -- int64.
Column Rte_crim has data type -- int64.
Column Rte_alco has data type -- int64.
Column Propt_envi has data type -- object.
Column Prop_depr has data type -- float64.
Column Propt_HPI has data type -- object.
Column Prop_fru has data type -- float64.
Column Prop_bev has data type -- float64.
Column Prop_hyp has data type -- float64.
Column Prop_marj has data type -- float64.

In [45]:
# Change select columns to string
new_community_health_df[["GEONAME", 
                         "Prop_Eng", 
                         "No_farm", 
                         "Prop_obse", 
                         "Propt_envi", 
                         "Propt_HPI"]] = new_community_health_df[["GEONAME", 
                                                                  "Prop_Eng", 
                                                                  "No_farm", 
                                                                  "Prop_obse", 
                                                                  "Propt_envi", 
                                                                  "Propt_HPI"]].astype(str)

In [46]:
# Check for null values
for column in new_community_health_df.columns:
    print(f"Column {column} has {new_community_health_df[column].isnull().sum()} null values.")

Column GEONAME has 0 null values.
Column Pop_Tot has 0 null values.
Column Prop_18y has 0 null values.
Column Prop_64y has 0 null values.
Column Prop_65y+ has 0 null values.
Column Prop_Blk has 0 null values.
Column Prop_Lat has 0 null values.
Column Prop_Whi has 0 null values.
Column Prop_Asi has 0 null values.
Column Prop_Ami has 0 null values.
Column Prop_NHO has 0 null values.
Column Prop_FPL1 has 0 null values.
Column Prop_FPL2 has 0 null values.
Column Prop_forb has 0 null values.
Column Prop_Eng has 0 null values.
Column Prop_edLH has 0 null values.
Column Prop_edHG has 0 null values.
Column Prop_edSC has 0 null values.
Column Prop_edCG has 0 null values.
Column MHI has 0 null values.
Column Prop_groc has 0 null values.
Column Prop_60mi has 0 null values.
Column No_farm has 0 null values.
Column Prop_obse has 0 null values.
Column Prop_DM has 0 null values.
Column Rte_CVD has 0 null values.
Column Prop_ownr has 0 null values.
Column Prop_rentr has 0 null values.
Column No_hless has 0 null values.
Column Rte_crim has 0 null values.
Column Rte_alco has 0 null values.
Column Propt_envi has 0 null values.
Column Prop_depr has 0 null values.
Column Propt_HPI has 0 null values.
Column Prop_fru has 0 null values.
Column Prop_bev has 0 null values.
Column Prop_hyp has 0 null values.
Column Prop_marj has 0 null values.

In [47]:
# Check shape
new_community_health_df.shape

(87, 38)

In [48]:
# Export to csv
new_community_health_df.to_csv("./Resources/Clean/clean_community_health.csv")

**NEXT STEP**: Review and update 'GEONAME' in SQL.