In [1]:
import pandas as pd
bNew = True

# First Iteration
It appends longitude & latitude coordinates to the LA County Health Profile CSV using USZipCA.csv based on GeoNames
This was before Esther's lookup table was known, so this will be converted to use that lookup table in the next ieration.

In [2]:
if bNew:
    dfC = pd.read_csv("data/USZipsCA.csv")
else:
    dfC = pd.read_csv("zip_codes_CA.csv")
sListDuplicates = []
dfC.head()

,zip,lat,lng,city,state_id,state_name,zcta,parent_zcta,population,density,county_fips,county_name,county_weights,county_names_all,county_fips_all,imprecise,military,timezone
0,90001,33.97397,-118.24953,Los Angeles,CA,California,True,NaN,58975,6295.8,6037,Los Angeles,{'06037':100},Los Angeles,6037,False,False,America/Los_Angeles
1,90002,33.94906,-118.24673,Los Angeles,CA,California,True,NaN,53111,6458.9,6037,Los Angeles,{'06037':100},Los Angeles,6037,False,False,America/Los_Angeles
2,90003,33.96411,-118.27370,Los Angeles,CA,California,True,NaN,72741,7204.7,6037,Los Angeles,{'06037':100},Los Angeles,6037,False,False,America/Los_Angeles
3,90004,34.07621,-118.31084,Los Angeles,CA,California,True,NaN,61586,7876.3,6037,Los Angeles,{'06037':100},Los Angeles,6037,False,False,America/Los_Angeles
4,90005,34.05915,-118.30643,Los Angeles,CA,California,True,NaN,39479,13421.3,6037,Los Angeles,{'06037':100},Los Angeles,6037,False,False,America/Los_Angeles

In [3]:
dfGeo = pd.read_csv("data/Los_Angeles_County_City_and_Community_Health_Profiles_2018.csv")
dfGeo.head()

,GEONAME,Pop_Tot,Prop_18y,Prop_64y,Prop_65y+,Prop_Blk,Prop_Lat,Prop_Whi,Prop_Asi,Prop_Ami,...,Rte_mein,Rte_cein,Rte_luin,Prop_fru,Prop_bev,Prop_hyp,Prop_marj,Prop_HI,Prop_grad,Prop_trua
0,Alhambra,86705,0.1831,0.6504,0.1665,0.0133,0.3435,0.0913,0.5498,0.0014,...,**,**,34.6,0.2,0.2,0.2,0.1,0.0,1.0,0.1
1,Altadena,42525,0.2072,0.6221,0.1707,0.2374,0.2905,0.4129,0.0553,0.0019,...,33.8,**,35.3,0.1,0.3,0.3,0.2,0.1,0.9,0.4
2,Arcadia,56992,0.1794,0.6389,0.1817,0.0115,0.1250,0.2304,0.6315,0.0014,...,22.0,**,29.5,0.1,0.2,0.2,0.0,0.0,1.0,0.1
3,Azusa,49479,0.2507,0.6538,0.0956,0.0292,0.6838,0.1938,0.0895,0.0024,...,**,**,29.7,0.1,0.4,0.2,0.1,0.0,0.9,0.0
4,Baldwin Park,74438,0.2623,0.6330,0.1047,0.0099,0.7934,0.0432,0.1514,0.0012,...,**,**,26.5,0.1,0.4,0.3,0.1,0.0,1.0,0.4

In [4]:
empty_dataframe = pd.DataFrame()
#list_dataframe = pd.DataFrame([1, 2, 3])
#print(result_dataframe)

if (bNew):
    sLabelCounty = 'county_name' #'county'
    sLabelLat = 'lat' #'latitude'
    sLabelLng = 'lng' #'longitude'
else:
    sLabelCounty = 'county'
    sLabelLat = 'latitude'
    sLabelLng = 'longitude'
    
for i, row in dfGeo.iterrows():
    sGeoName = row['GEONAME']
    #dfC.loc[dfC['county'] == sGeoName].count()
    if (dfC.loc[dfC[sLabelCounty] == sGeoName].count()[sLabelCounty] > 1):
        #sListDuplicates.Add(dfC.loc[dfC['county'] == sGeoName])
        result_dataframe = empty_dataframe.append(dfC.loc[dfC[sLabelCounty] == sGeoName])
        dlat = dfC.loc[dfC[sLabelCounty] == sGeoName][sLabelLat].values[0]
        dlng = dfC.loc[dfC[sLabelCounty] == sGeoName][sLabelLng].values[0]
    elif (dfC.loc[dfC[sLabelCounty] == sGeoName].count()[sLabelCounty] > 0):    
        dlat = dfC.loc[dfC[sLabelCounty] == sGeoName][sLabelLat].values[0]
        dlng = dfC.loc[dfC[sLabelCounty] == sGeoName][sLabelLng].values[0]
    else:
        if (dfC.loc[dfC['city'] == sGeoName].count()['city'] > 1):
            #sListDuplicates.Add(dfC.loc[dfC['county'] == sGeoName])
            result_dataframe = empty_dataframe.append(dfC.loc[dfC['city'] == sGeoName])
            dlat = dfC.loc[dfC['city'] == sGeoName][sLabelLat].values[0]
            dlng = dfC.loc[dfC['city'] == sGeoName][sLabelLng].values[0]
        elif (dfC.loc[dfC['city'] == sGeoName].count()['city'] > 0):

            dlat = dfC.loc[dfC['city'] == sGeoName][sLabelLat].values[0]
            dlng = dfC.loc[dfC['city'] == sGeoName][sLabelLng].values[0]
        else:
            dlat = -1
            dlng = -1
        #dlat = -1
        #dlng = -1
    #lng = row['longitude']
    #city = citipy.nearest_city(lat, lng).city_name
    dfGeo.at[i, sLabelLat] = dlat
    dfGeo.at[i, sLabelLng] = dlng
                                                  
    #df3.set_value(i, 'City', city)
    print(str(dlat) + ', ' + str(dlng) + ': ' + sGeoName)

#dfC

34.090759999999996, -118.12756: Alhambra
34.195440000000005, -118.13796: Altadena
34.13599, -118.02675: Arcadia
34.265570000000004, -117.86721999999999: Azusa
34.09641, -117.96816000000001: Baldwin Park
-1, -1: Bell
33.97074, -118.17083999999998: Bell Gardens
33.888020000000004, -118.12708: Bellflower
34.10103, -118.41476000000002: Beverly Hills
34.200520000000004, -118.29583000000001: Burbank
34.12426, -118.67012: Calabasas
33.82124, -118.26441000000001: Carson
33.86786, -118.06873999999999: Cerritos
34.12853, -117.71561000000001: Claremont
33.880790000000005, -118.23607: Compton
34.09726, -117.90616000000001: Covina
-1, -1: Cudahy
33.99722, -118.3946: Culver City
33.98822, -117.81446000000001: Diamond Bar
33.9568, -118.11868999999999: Downey
-1, -1: East Los Angeles
34.07877, -118.04063000000001: El Monte
-1, -1: Florence-Graham
33.8914, -118.29737: Gardena
34.17031, -118.28913: Glendale
34.118790000000004, -117.85396000000001: Glendora
33.999309999999994, -117.97325: Hacienda Heights
33.91437, -118.3493: Hawthorne
33.97703, -118.2173: Huntington Park
33.956520000000005, -118.35864: Inglewood
33.902409999999996, -118.0092: La Mirada
34.028890000000004, -117.93732: La Puente
34.16084, -117.77278000000001: La Verne
33.84901, -118.14672: Lakewood
34.71569, -118.15122: Lancaster
33.888290000000005, -118.35125: Lawndale
33.750209999999996, -118.21141000000001: Long Beach
-1, -1: Los Angeles Council District  1
-1, -1: Los Angeles Council District  2
-1, -1: Los Angeles Council District  3
-1, -1: Los Angeles Council District  4
-1, -1: Los Angeles Council District  5
-1, -1: Los Angeles Council District  6
-1, -1: Los Angeles Council District  7
-1, -1: Los Angeles Council District  8
-1, -1: Los Angeles Council District  9
-1, -1: Los Angeles Council District 10
-1, -1: Los Angeles Council District 11
-1, -1: Los Angeles Council District 12
-1, -1: Los Angeles Council District 13
-1, -1: Los Angeles Council District 14
-1, -1: Los Angeles Council District 15
-1, -1: Los Angeles, City of
33.92365, -118.20053: Lynwood
33.8895, -118.39718: Manhattan Beach
33.98805, -118.18597: Maywood
34.15213, -118.00068999999999: Monrovia
34.01508, -118.11073: Montebello
34.050959999999996, -118.1446: Monterey Park
33.90685, -118.08263000000001: Norwalk
34.41325, -118.09161: Palmdale
33.89743, -118.16481999999999: Paramount
34.146570000000004, -118.13942: Pasadena
33.988820000000004, -118.09063: Pico Rivera
34.04179, -117.75691: Pomona
33.75545, -118.36393000000001: Rancho Palos Verdes
33.83077, -118.38458: Redondo Beach
34.0644, -118.08365: Rosemead
33.97661, -117.8997: Rowland Heights
34.110040000000005, -117.80981000000001: San Dimas
34.28671, -118.4351: San Fernando
34.1144, -118.08944: San Gabriel
34.43358, -118.50072: Santa Clarita
34.01546, -118.49255: Santa Monica
33.94467, -118.19268000000001: South Gate
34.1102, -118.15735: South Pasadena
-1, -1: South Whittier
34.10148, -118.05547: Temple City
33.8334, -118.31426: Torrance
-1, -1: Valinda
34.01831, -117.85463: Walnut
34.06735, -117.93771000000001: West Covina
34.09386, -118.38171000000001: West Hollywood
-1, -1: West Whittier-Los Nietos
-1, -1: Westmont
34.008340000000004, -118.03135: Whittier
-1, -1: Los Angeles County

In [5]:
#dfGeo = pd.read_csv("Los_Angeles_County_City_and_Community_Health_Profiles_2018.csv")
#dfGeo.head()
dfGeo.to_csv(r'Los_Angeles_County_City_and_Community_Health_Profiles_2018_LatLng.csv')