In [1]:
import pandas as pd

In [4]:
data = pd.read_csv("./Resources/Los_Angeles_County_City_and_Community_Health_Profiles_2018.csv", index_col = 0)
data

,Pop_Tot,Prop_18y,Prop_64y,Prop_65y+,Prop_Blk,Prop_Lat,Prop_Whi,Prop_Asi,Prop_Ami,Prop_NHO,...,Rte_mein,Rte_cein,Rte_luin,Prop_fru,Prop_bev,Prop_hyp,Prop_marj,Prop_HI,Prop_grad,Prop_trua
GEONAME,,,,,,,,,,,,,,,,,,,,,
Alhambra,86705,0.1831,0.6504,0.1665,0.0133,0.3435,0.0913,0.5498,0.0014,0.0007,...,**,**,34.6,0.2,0.2,0.2,0.1,0.0,1.0,0.1
Altadena,42525,0.2072,0.6221,0.1707,0.2374,0.2905,0.4129,0.0553,0.0019,0.0020,...,33.8,**,35.3,0.1,0.3,0.3,0.2,0.1,0.9,0.4
Arcadia,56992,0.1794,0.6389,0.1817,0.0115,0.1250,0.2304,0.6315,0.0014,0.0003,...,22.0,**,29.5,0.1,0.2,0.2,0.0,0.0,1.0,0.1
Azusa,49479,0.2507,0.6538,0.0956,0.0292,0.6838,0.1938,0.0895,0.0024,0.0013,...,**,**,29.7,0.1,0.4,0.2,0.1,0.0,0.9,0.0
Baldwin Park,74438,0.2623,0.6330,0.1047,0.0099,0.7934,0.0432,0.1514,0.0012,0.0008,...,**,**,26.5,0.1,0.4,0.3,0.1,0.0,1.0,0.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
West Hollywood,35797,0.0639,0.7801,0.1560,0.0310,0.1081,0.7984,0.0603,0.0014,0.0008,...,30.6,**,53.0,0.4,0.2,0.2,0.2,**,0.6,0.2
West Whittier-Los Nietos,25441,0.2426,0.6253,0.1321,0.0080,0.8775,0.0954,0.0147,0.0032,0.0013,...,**,**,**,0.1,0.4,0.2,0.1,0.0,1.0,0.3
Westmont,32835,0.2823,0.6208,0.0968,0.4945,0.4912,0.0096,0.0025,0.0012,0.0009,...,**,**,46.9,0.2,0.4,0.3,0.0,0.1,0.8,0.4
Whittier,88078,0.2304,0.6385,0.1311,0.0098,0.6750,0.2752,0.0361,0.0028,0.0011,...,29.5,**,35.1,0.2,0.3,0.3,0.1,0.0,0.9,0.4
Los Angeles County,10227450,0.2253,0.6471,0.1276,0.0846,0.4876,0.2804,0.1431,0.0019,0.0024,...,21.6,7.7,36.4,0.1,0.4,0.2,0.1,0.0,0.8,0.3

In [9]:
print(data.columns)

Index(['Pop_Tot', 'Prop_18y', 'Prop_64y', 'Prop_65y+', 'Prop_Blk', 'Prop_Lat',
       'Prop_Whi', 'Prop_Asi', 'Prop_Ami', 'Prop_NHO', 'Prop_FPL1',
       'Prop_FPL2', 'Prop_forb', 'Prop_Eng', 'LE', 'Prop_prsc', 'Prop_3rdg',
       'Prop_edLH', 'Prop_edHG', 'Prop_edSC', 'Prop_edCG', 'MHI', 'No_libr',
       'Prop_empl', 'Prop_emsu', 'Prop_vote', 'Rte_resp', 'Prop_PA',
       'Prop_groc', 'Prop_60mi', 'No_farm', 'No_EBT', 'Prop_foin', 'No_CalF',
       'Rte_CalF', 'Prop_FRPM', 'Prop_obse', 'Prop_DM', 'Rte_coin', 'Rte_brin',
       'Prop_smok', 'Rte_luca', 'Rte_COPD', 'Rte_CVD', 'Prop_hbu1',
       'Prop_hbu2', 'Prop_ownr', 'Prop_rentr', 'No_hless', 'Prop_asth',
       'Rte_crim', 'Rte_hom', 'Rte_alco', 'Propt_envi', 'No_gasw', 'Rte_te17',
       'Rte_te19', 'Prop_LBW', 'Rte_IMR', 'Prop_1stt', 'Prop_depr', 'Rte_suic',
       'Rte_UOD', 'Rte_syin', 'Rte_goin', 'Rte_hiv', 'Prop_uinC', 'Prop_uinA',
       'Prop_duinC', 'Prop_duinA', 'Propt_HPI', 'Rte_mein', 'Rte_cein',
       'Rte_luin', 'Prop_fru', 'Prop_bev', 'Prop_hyp', 'Prop_marj', 'Prop_HI',
       'Prop_grad', 'Prop_trua'],
      dtype='object')

In [13]:
data.isnull().count()

Pop_Tot      87
Prop_18y     87
Prop_64y     87
Prop_65y+    87
Prop_Blk     87
             ..
Prop_hyp     87
Prop_marj    87
Prop_HI      87
Prop_grad    87
Prop_trua    87
Length: 81, dtype: int64

In [15]:
scores = data[["Propt_envi", "Propt_HPI"]]
scores

                         Propt_envi Propt_HPI
GEONAME
Alhambra                          6      43.3
Altadena                         62      75.5
Arcadia                          27      73.4
Azusa                            48      34.2
Baldwin Park                      9      22.3
...                             ...       ...
West Hollywood                   29      70.6
West Whittier-Los Nietos         26      41.2
Westmont                         69       0.6
Whittier                         63      53.8
Los Angeles County                -         -

[87 rows x 2 columns]

* Propt_envi = California Healthy Places Index Clean Environment Score rank percentile
* Propt_HPI = California Healthy Places Index (HPI) Score rank percentile